using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Web.Security;
using RaaiVan.Modules.GlobalUtilities;
using RaaiVan.Modules.GlobalUtilities.DBCompositeTypes;

namespace RaaiVan.Modules.Users
{
    public static class UsersController
    {
        private static string GetFullyQualifiedName(string name)
        {
            return "[dbo]." + "[USR_" + name + "]"; //'[dbo].' is database owner and 'CN_' is module qualifier
        }

        public static List<Password> get_last_passwords(Guid? applicationId, Guid userId, bool? autoGenerated, int? count)
        {
            return USRParsers.last_passwords(DBConnector.read(applicationId, GetFullyQualifiedName("GetLastPasswords"),
                userId, autoGenerated, count));
        }

        public static DateTime? get_last_password_date(Guid? applicationId, Guid userId)
        {
            return DBConnector.get_date(applicationId, GetFullyQualifiedName("GetLastPasswordDate"), userId);
        }

        public static void get_current_password(Guid? applicationId, Guid userId, ref string password, ref string passwordSalt)
        {
            DBResultSet results = DBConnector.read(applicationId, GetFullyQualifiedName("GetCurrentPassword"), userId);
            USRParsers.password(results, ref password, ref passwordSalt);
        }

        public static void get_current_password(Guid? applicationId, string username,
            ref string password, ref string passwordSalt)
        {
            Guid? userId = get_user_id(applicationId, username);
            if(userId.HasValue) get_current_password(applicationId, userId.Value, ref password, ref passwordSalt);
        }

        public static bool create_user(Guid? applicationId, User info, bool passAutoGenerated)
        {
            if (info == null || string.IsNullOrEmpty(info.UserName)) return false;

            if (!info.UserID.HasValue || info.UserID == Guid.Empty) info.UserID = Guid.NewGuid();

            if (string.IsNullOrEmpty(info.Password))
            {
                info.Password = info.UserName;
                while (info.Password.Length < 5) info.Password += info.UserName;

                passAutoGenerated = true;
            }

            info.PasswordSalt = UserUtilities.generate_password_salt();

            string saltedPassword = UserUtilities.encode_password(info.Password, info.PasswordSalt);

            string email = info.Emails == null || info.Emails.Count != 1 ||
                string.IsNullOrEmpty(info.Emails.First().Address) ? null : info.Emails.First().Address;

            string number = info.PhoneNumbers == null || info.PhoneNumbers.Count != 1 ||
                string.IsNullOrEmpty(info.PhoneNumbers.First().Number) ? null : info.PhoneNumbers.First().Number;

            return DBConnector.succeed(applicationId, GetFullyQualifiedName("CreateUser"),
                applicationId, info.UserID, info.UserName, info.FirstName, info.LastName, saltedPassword,
                info.PasswordSalt, PublicMethods.sha1(info.Password), passAutoGenerated, email, number, DateTime.Now);
        }

        public static bool create_temporary_user(Guid? applicationId, User info, bool passAutoGenerated,
            string emailSubject, string confirmationEmailBody, DateTime? expirationDate, string activationCode,
            Guid? invitationId, ref string errorMessage)
        {
            if (invitationId == Guid.Empty) invitationId = null;

            bool succeed = false;

            if (string.IsNullOrEmpty(info.UserName) || string.IsNullOrEmpty(confirmationEmailBody)) return succeed;

            string email = info.Emails.Count == 0 ? string.Empty : info.Emails.First().Address;
            string phoneNumber = info.PhoneNumbers.Count == 0 ? string.Empty : info.PhoneNumbers.First().Number;

            if (string.IsNullOrEmpty(email) && string.IsNullOrEmpty(phoneNumber)) return succeed;

            if (string.IsNullOrEmpty(info.PasswordSalt) || string.IsNullOrEmpty(info.Password))
            {
                info.PasswordSalt = UserUtilities.generate_password_salt();
                info.Password = UserUtilities.generate_password();
                info.SaltedPassword = UserUtilities.encode_password(info.Password, info.PasswordSalt);

                passAutoGenerated = true;
            }

            Func<DBResultSet, bool> action = (dbRes) =>
            {
                succeed = dbRes.get_table().GetBool(row: 0, column: 0, defaultValue: false).Value &&
                    PublicMethods.send_email(applicationId, email, emailSubject, confirmationEmailBody);
                return succeed;
            };

            DBConnector.read(action, applicationId, GetFullyQualifiedName("CreateTemporaryUser"),
                info.UserID, info.UserName, info.FirstName, info.LastName, info.SaltedPassword, info.PasswordSalt,
                PublicMethods.sha1(info.Password), passAutoGenerated, email, phoneNumber, DateTime.Now, expirationDate,
                activationCode, invitationId);

            return succeed;
        }

        public static bool activate_temporary_user(Guid? applicationId, string activationCode, ref string errorMessage)
        {
            return DBConnector.succeed(applicationId, ref errorMessage, GetFullyQualifiedName("ActivateTemporaryUser"),
                activationCode, DateTime.Now);
        }

        public static Guid? get_invitation_id(Guid applicationId, string email, bool checkIfNotUsed)
        {
            return DBConnector.get_guid(applicationId, GetFullyQualifiedName("GetInvitationID"), applicationId, email, checkIfNotUsed);
        }

        public static bool is_invited(Guid applicationId, string email)
        {
            return get_invitation_id(applicationId, email, false).HasValue;
        }

        public static bool invite_user(Guid applicationId, Guid invitationId, string email,
            bool isExistingInvitation, Guid currentUserId, string emailSubject, string emailBody)
        {
            bool succeed = false;

            if (string.IsNullOrEmpty(email)) return succeed;

            if (isExistingInvitation) return PublicMethods.send_email(applicationId, email, emailSubject, emailBody);

            Func<DBResultSet, bool> action = (dbRes) =>
            {
                succeed = dbRes.get_table().GetBool(row: 0, column: 0, defaultValue: false).Value &&
                    PublicMethods.send_email(applicationId, email, emailSubject, emailBody);
                return succeed;
            };

            DBConnector.read(action, applicationId, GetFullyQualifiedName("InviteUser"),
                applicationId, invitationId, email, currentUserId, DateTime.Now);

            return succeed;
        }

        public static int get_invited_users_count(Guid applicationId, Guid? invitorUserId)
        {
            return DBConnector.get_int(applicationId, GetFullyQualifiedName("GetInvitedUsersCount"), applicationId, invitorUserId);
        }

        public static List<Invitation> get_user_invitations(Guid applicationId, 
            Guid? senderUserId, int? count, long? lowerBoundary, ref long totalCount)
        {
            DBResultSet results = DBConnector.read(applicationId, GetFullyQualifiedName("GetUserInvitations"),
                applicationId, senderUserId, count, lowerBoundary);

            return USRParsers.invitations(results, ref totalCount);
        }

        public static List<Application> get_current_invitations(Guid userId, string email)
        {
            List<Guid> appIds = DBConnector.get_guid_list(null, GetFullyQualifiedName("GetCurrentInvitations"), userId, email);
            return GlobalController.get_applications(appIds);
        }

        public static Guid? get_invitation_application_id(Guid invitationId, bool checkIfNotUsed)
        {
            return DBConnector.get_guid(null, GetFullyQualifiedName("GetInvitationApplicationID"), invitationId, checkIfNotUsed);
        }

        public static bool set_pass_reset_ticket(Guid? applicationId, Guid userId, Guid ticket, 
            string email, string emailSubject, string emailBody, bool sendEmail = true)
        {
            bool succeed = false;

            if (sendEmail && string.IsNullOrEmpty(email)) return succeed;

            Func<DBResultSet, bool> action = (dbRes) =>
            {
                succeed = dbRes.get_table().GetBool(row: 0, column: 0, defaultValue: false).Value &&
                    PublicMethods.send_email(applicationId, email, emailSubject, emailBody);
                return succeed;
            };

            DBConnector.read(!sendEmail ? null : action, applicationId, GetFullyQualifiedName("SetPassResetTicket"), userId, ticket);

            return succeed;
        }

        public static bool set_pass_reset_ticket(Guid applicationId, string username, Guid ticket, 
            string email, string emailSubject, string emailBody, bool sendEmail = true)
        {
            Guid? userId = get_user_id(applicationId, username);
            return userId.HasValue && set_pass_reset_ticket(applicationId, userId.Value, ticket, email, emailSubject, emailBody, sendEmail);
        }

        public static Guid? get_pass_reset_ticket(Guid? applicationId, Guid userId)
        {
            return DBConnector.get_guid(applicationId, GetFullyQualifiedName("GetPassResetTicket"), userId);
        }

        public static Guid? get_pass_reset_ticket(Guid? applicationId, string username)
        {
            Guid? userId = get_user_id(applicationId, username);
            return !userId.HasValue ? null : get_pass_reset_ticket(applicationId, userId.Value);
        }
        
        public static int get_users_count(Guid applicationId, 
            DateTime? creationDateLowerThreshold = null, DateTime? creationDateUpperThreshold = null)
        {
            return DBConnector.get_int(applicationId, GetFullyQualifiedName("GetUsersCount"),
                applicationId, creationDateLowerThreshold, creationDateUpperThreshold);
        }

        public static List<Guid> get_user_ids(Guid? applicationId, List<string> usernames)
        {
            DBCompositeType<StringTableType> usernamesParam = new DBCompositeType<StringTableType>()
                .add(usernames.Select(un => new StringTableType(un)).ToList());

            return DBConnector.get_guid_list(applicationId, GetFullyQualifiedName("GetUserIDs"), applicationId, usernamesParam);
        }

        public static Guid? get_user_id(Guid? applicationId, string username)
        {
            List<Guid> ids = get_user_ids(applicationId, new List<string>() { username });

            if (!string.IsNullOrEmpty(username) && (ids == null || ids.Count == 0) && RaaiVanSettings.SAASBasedMultiTenancy)
            {
                bool isEmail = PublicMethods.is_email(username);
                bool isNumber = PublicMethods.parse_long(username).HasValue;

                if (isEmail)
                {
                    List<EmailAddress> emails = get_email_owners(applicationId, new List<string>() { username })
                        .Where(x => x.IsMain.HasValue && x.IsMain.Value).ToList();
                    if (emails != null && emails.Count == 1 && emails.First().UserID.HasValue) ids.Add(emails.First().UserID.Value);
                }
                else if (isNumber)
                {
                    List<PhoneNumber> numbers = get_phone_owners(applicationId, new List<string>() { username })
                        .Where(x => x.IsMain.HasValue && x.IsMain.Value).ToList();
                    if (numbers != null && numbers.Count == 1 && numbers.First().UserID.HasValue) ids.Add(numbers.First().UserID.Value);
                }
            }

            return ids != null && ids.Count == 1 ? (Guid?)ids[0] : null;
        }

        public static List<User> get_users(Guid applicationId, string searchText, 
            long? lowerBoundary, int? count, bool? isOnline, ref long totalCount, bool? isApproved = true)
        {
            DBResultSet results = DBConnector.read(applicationId, GetFullyQualifiedName("GetUsers"),
                applicationId, ProviderUtil.get_search_text(searchText), lowerBoundary, count, isOnline, isApproved, DateTime.Now);

            return USRParsers.users(results, ref totalCount);
        }

        public static List<User> get_users(Guid applicationId, string searchText, long? lowerBoundary = null, 
            int? count = null, bool? isOnline = null, bool? isApproved = true)
        {
            long totalCount = 0;
            return get_users(applicationId, searchText, lowerBoundary, count, isOnline, ref totalCount, isApproved);
        }

        public static List<User> get_users(Guid? applicationId, List<Guid> userIds)
        {
            return userIds == null || userIds.Count == 0 ? new List<User>() :
                USRParsers.users(DBConnector.read(applicationId, GetFullyQualifiedName("GetUsersByIDs"),
                applicationId, ProviderUtil.list_to_string<Guid>(userIds), ','));
        }

        public static User get_user(Guid? applicationId, Guid userId)
        {
            return get_users(applicationId, new List<Guid>() { userId }).FirstOrDefault();
        }

        public static List<User> get_users(Guid? applicationId, List<string> usernames)
        {
            return get_users(applicationId, get_user_ids(applicationId, usernames));
        }

        public static User get_user(Guid? applicationId, string username)
        {
            return get_users(applicationId, new List<string>() { username }).FirstOrDefault();
        }

        public static List<ApplicationUsers> get_application_users_partitioned(List<Guid> applicationIds, int? count)
        {
            return USRParsers.application_users(DBConnector.read(null, GetFullyQualifiedName("GetApplicationUsersPartitioned"),
                string.Join(",", applicationIds), ',', count));
        }

        public static List<AdvancedUserSearch> advanced_user_search(Guid applicationId, string searchText,
            List<Guid> nodeTypeIds, List<Guid> nodeIds, bool? members, bool? experts, bool? contributors, 
            bool? propertyOwners, bool? resume, long? lowerBoundary, int? count, ref long totalCount)
        {
            DBResultSet results = DBConnector.read(applicationId, GetFullyQualifiedName("AdvancedUserSearch"),
                applicationId, searchText, ProviderUtil.get_search_text(searchText, false),
                ProviderUtil.list_to_string<Guid>(nodeTypeIds), ProviderUtil.list_to_string<Guid>(nodeIds),
                ',', members, experts, contributors, propertyOwners, resume, lowerBoundary, count);

            return USRParsers.advanced_user_search(results, ref totalCount);
        }

        public static List<AdvancedUserSearchMeta> advanced_user_search_meta(Guid applicationId, 
            Guid userId, string searchText, List<Guid> nodeTypeIds, List<Guid> nodeIds, 
            bool? members, bool? experts, bool? contributors, bool? propertyOwners)
        {
            return USRParsers.advanced_user_search_meta(DBConnector.read(applicationId, GetFullyQualifiedName("AdvancedUserSearchMeta"),
                applicationId, userId, ProviderUtil.get_search_text(searchText, false),
                ProviderUtil.list_to_string<Guid>(nodeTypeIds), ProviderUtil.list_to_string<Guid>(nodeIds),
                ',', members, experts, contributors, propertyOwners));
        }

        public static User get_system_user(Guid? applicationId)
        {
            if (RaaiVanSettings.SAASBasedMultiTenancy) applicationId = null;

            DBResultSet results = DBConnector.read(applicationId, GetFullyQualifiedName("GetSystemUser"), applicationId);

            return USRParsers.users(results, systemAlso: true).FirstOrDefault();
        }

        public static bool create_admin_user(Guid applicationId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("CreateAdminUser"), applicationId);
        }

        public static List<string> get_not_existing_users(Guid applicationId, List<string> usernames)
        {
            DBCompositeType<StringTableType> usernamesParam = new DBCompositeType<StringTableType>()
                .add(usernames.Select(un => new StringTableType(un)).ToList());

            return DBConnector.get_string_list(applicationId, GetFullyQualifiedName("GetNotExistingUsers"), 
                applicationId, usernamesParam);
        }

        public static bool register_item_visit(Guid applicationId, 
            Guid itemId, Guid userId, DateTime visitDate, VisitItemTypes itemType)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("RegisterItemVisit"),
                applicationId, itemId, userId, visitDate, itemType.ToString());
        }

        public static bool send_friendship_request(Guid applicationId, Guid userId, Guid receiverUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SendFriendshipRequest"),
                applicationId, userId, receiverUserId, DateTime.Now);
        }

        public static bool accept_friendship(Guid applicationId, Guid userId, Guid senderUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("AcceptFriendship"),
                applicationId, userId, senderUserId, DateTime.Now);
        }

        public static bool reject_friendship(Guid applicationId, Guid userId, Guid friendUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("RejectFriendship"), applicationId, userId, friendUserId);
        }

        public static List<Friend> get_friendship_status(Guid applicationId, 
            Guid userId, List<Guid> otherUserIds, bool? mutualsCount = false)
        {
            return USRParsers.friendship_statuses(DBConnector.read(applicationId, GetFullyQualifiedName("GetFriendshipStatus"),
                applicationId, userId, ProviderUtil.list_to_string<Guid>(otherUserIds), ',', mutualsCount));
        }

        public static Friend get_friendship_status(Guid applicationId, 
            Guid userId, Guid otherUserId, bool? mutualsCount = false)
        {
            List<Guid> uIds = new List<Guid>();
            uIds.Add(otherUserId);
            return get_friendship_status(applicationId, userId, uIds, mutualsCount).FirstOrDefault();
        }

        public static List<Guid> get_friend_ids(Guid applicationId, 
            Guid userId, bool? areFriends = null, bool? sent = null, bool? received = null)
        {
            return DBConnector.get_guid_list(applicationId, GetFullyQualifiedName("GetFriendIDs"),
                applicationId, userId, areFriends, sent, received);
        }

        public static List<Friend> get_friends(Guid applicationId, Guid userId, List<Guid> friendIds, 
            bool? mutualsCount, int? count, long? lowerBoundary, ref long totalCount, 
            bool? areFriends = null, bool? isSender = null, string searchText = null)
        {
            DBResultSet results = DBConnector.read(applicationId, GetFullyQualifiedName("GetFriends"),
                applicationId, userId, ProviderUtil.list_to_string<Guid>(friendIds), ',', mutualsCount,
                areFriends, isSender, ProviderUtil.get_search_text(searchText), count, lowerBoundary);

            return USRParsers.friends(results, ref totalCount);
        }

        public static List<Friend> get_friends(Guid applicationId, Guid userId, bool? mutualsCount, 
            int? count, long? lowerBoundary, ref long totalCount, 
            bool? areFriends = null, bool? isSender = null, string searchText = null)
        {
            return get_friends(applicationId, userId, new List<Guid>(), mutualsCount, 
                count, lowerBoundary, ref totalCount, areFriends, isSender, searchText);
        }

        public static int get_friends_count(Guid applicationId, 
            Guid userId, bool? areFriends = null, bool? sent = null, bool? received = null)
        {
            return DBConnector.get_int(applicationId, GetFullyQualifiedName("GetFriendsCount"),
                applicationId, userId, areFriends, sent, received);
        }

        public static List<EmailContactStatus> get_email_contacts_status(Guid applicationId, 
            Guid userId, List<string> emails, bool? saveEmails = null)
        {
            if (emails == null) emails = new List<string>();

            DBCompositeType<StringTableType> emailsParam = new DBCompositeType<StringTableType>()
                .add(emails.Select(e => new StringTableType(e)).ToList());

            return USRParsers.email_contacts_status(DBConnector.read(applicationId, GetFullyQualifiedName("GetEmailContactsStatus"),
                applicationId, userId, emailsParam, saveEmails, DateTime.Now));
        }

        public static bool update_friend_suggestions(Guid applicationId, Guid? userId = null)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("UpdateFriendSuggestions"), applicationId, userId);
        }
        
        public static List<FriendSuggestion> get_friend_suggestions(Guid applicationId, Guid userId, 
            int? count, long? lowerBoundary, ref long totalCount)
        {
            DBResultSet results = DBConnector.read(applicationId, GetFullyQualifiedName("GetFriendSuggestions"),
                applicationId, userId, count, lowerBoundary);

            return USRParsers.friend_suggestions(results, ref totalCount);
        }
        
        public static bool set_theme(Guid? applicationId, Guid userId, string theme)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetTheme"), userId, theme); 
        }

        public static string get_theme(Guid? applicationId, Guid userId)
        {
            return DBConnector.get_string(applicationId, GetFullyQualifiedName("GetTheme"), userId);
        }

        public static List<Guid> get_approved_user_ids(Guid applicationId, List<Guid> userIds)
        {
            return DBConnector.get_guid_list(applicationId, GetFullyQualifiedName("GetApprovedUserIDs"),
                applicationId, ProviderUtil.list_to_string(userIds), ',');
        }

        public static bool set_last_activity_date(Guid? applicationId, Guid userId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetLastActivityDate"), userId, DateTime.Now);
        }

        public static bool add_or_modify_remote_server(Guid applicationId, Guid serverId, Guid userId,
            string name, string url, string username, byte[] password)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("AddOrModifyRemoteServer"),
                applicationId, serverId, userId, name, url, username, password, DateTime.Now);
        }

        public static bool remove_remote_server(Guid applicationId, Guid serverId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("RemoveRemoteServer"), applicationId, serverId);
        }

        private static List<RemoteServer> get_remote_servers(Guid applicationId, Guid? serverId)
        {
            return USRParsers.remote_servers(DBConnector.read(applicationId, GetFullyQualifiedName("GetRemoteServers"),
                applicationId, serverId));
        }

        public static List<RemoteServer> get_remote_servers(Guid applicationId)
        {
            return get_remote_servers(applicationId, serverId: null);
        }

        public static RemoteServer get_remote_server(Guid applicationId, Guid serverId)
        {
            return get_remote_servers(applicationId, serverId).FirstOrDefault();
        }

        /* Profile */

        public static bool set_first_and_last_name(Guid? applicationId, Guid userId, string firstName, string lastName)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetFirstAndLastName"),
                userId, firstName, lastName);
        }

        public static bool set_username(Guid applicationId, Guid userId, string userName)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetUserName"), applicationId, userId, userName);
        }

        public static bool set_password(Guid? applicationId, Guid userId, 
            string password, bool ignorePasswordPolicy, bool autoGenerated, ref string errorMessage)
        {
            if (!ignorePasswordPolicy && 
                !UserUtilities.check_password_policy(applicationId, password, null, ref errorMessage)) return false;

            Password pass = new Password(password);

            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetPassword"),
                userId, pass.Salted, pass.Salt, pass.Encrypted, autoGenerated, DateTime.Now);
        }

        public static bool set_password(Guid? applicationId, string username, string password,
            bool ignorePasswordPolicy, bool autoGenerated, ref string errorMessage)
        {
            Guid? userId = get_user_id(applicationId, username);

            return userId.HasValue && set_password(applicationId, userId.Value, password, 
                ignorePasswordPolicy, autoGenerated, ref errorMessage);
        }

        private static User _locked(Guid? applicationId, Guid userId, bool? locked)
        {
            if (locked.HasValue)
            {
                return DBConnector.succeed(applicationId, GetFullyQualifiedName("Locked"), userId, locked, DateTime.Now) ?
                    new User() { IsLockedOut = locked } : null;
            }
            else
            {
                return USRParsers.lockout_date(
                    DBConnector.read(applicationId, GetFullyQualifiedName("Locked"), userId, locked, DateTime.Now));
            }
        }

        public static bool lock_user(Guid? applicationId, Guid userId)
        {
            return _locked(applicationId, userId, locked: true) != null;
        }

        public static bool lock_user(Guid? applicationId, string username)
        {
            Guid? userId = get_user_id(applicationId, username);
            return userId.HasValue && lock_user(applicationId, userId.Value);
        }

        public static bool unlock_user(Guid? applicationId, Guid userId)
        {
            return _locked(applicationId, userId, locked: false) != null;
        }

        public static bool unlock_user(Guid? applicationId, string username)
        {
            Guid? userId = get_user_id(applicationId, username);
            return userId.HasValue && unlock_user(applicationId, userId.Value);
        }

        public static User locked(Guid? applicationId, Guid userId)
        {
            return _locked(applicationId, userId, locked: null);
        }

        public static User locked(Guid? applicationId, string username)
        {
            Guid? userId = get_user_id(applicationId, username);
            return !userId.HasValue ? null : locked(applicationId, userId.Value);
        }

        public static int login_attempt(Guid? applicationId, Guid userId, bool succeed)
        {
            return DBConnector.get_int(applicationId, GetFullyQualifiedName("LoginAttempt"), userId, succeed);
        }

        public static int login_attempt(Guid? applicationId, string username, bool succeed)
        {
            Guid? userId = get_user_id(applicationId, username);
            return !userId.HasValue ? 0 : login_attempt(applicationId, userId.Value, succeed);
        }

        public static bool is_approved(Guid applicationId, Guid userId, bool? isApproved = null)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("IsApproved"), applicationId, userId, isApproved);
        }

        public static bool set_about_me(Guid? applicationId, Guid userId, string text)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetAboutMe"), userId, text);
        }

        public static bool set_city(Guid? applicationId, Guid userId, string city)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetCity"), userId, city);
        }

        public static bool set_organization(Guid applicationId, Guid userId, string organization)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetOrganization"), applicationId, userId, organization);
        }

        public static bool set_department(Guid applicationId, Guid userId, string department)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetDepartment"), applicationId, userId, department);
        }

        public static bool set_job_title(Guid applicationId, Guid userId, string jobTitle)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetJobTitle"), applicationId, userId, jobTitle);
        }

        public static bool set_employment_type(Guid applicationId, Guid userId, EmploymentType employmentType)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetEmploymentType"),
                applicationId, userId, employmentType.ToString());
        }

        public static bool set_birthday(Guid applicationId, Guid userId, DateTime birthday)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetBirthday"), applicationId, userId, birthday);
        }

        public static bool set_phone_number(Guid? applicationId, 
            Guid numberId, Guid userId, string phoneNumber, PhoneType phoneNumberType, Guid currentUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetPhoneNumber"),
                numberId, userId, phoneNumber, phoneNumberType.ToString(), currentUserId, DateTime.Now);
        }

        public static bool edit_phone_number(Guid? applicationId, 
            Guid numberId, string phoneNumber, PhoneType phoneType, Guid currentUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("EditPhoneNumber"),
                numberId, phoneNumber, phoneType.ToString(), currentUserId, DateTime.Now);
        }

        public static bool remove_phone_number(Guid? applicationId, Guid numberId, Guid currentUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("RemovePhoneNumber"), numberId, currentUserId, DateTime.Now);
        }

        public static bool set_main_phone(Guid? applicationId, Guid numberId, Guid userId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetMainPhone"), numberId, userId);
        }

        public static bool set_email_address(Guid? applicationId, Guid emailId, Guid userId, string address, Guid currentUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetEmailAddress"),
                emailId, userId, address, currentUserId, DateTime.Now);
        }

        public static bool edit_email_address(Guid? applicationId, Guid emailId, string address, Guid currentUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("EditEmailAddress"),
                emailId, address, currentUserId, DateTime.Now);
        }

        public static bool remove_email_address(Guid? applicationId, Guid emailId, Guid currentUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("RemoveEmailAddress"), emailId, currentUserId, DateTime.Now);
        }

        public static bool set_main_email(Guid? applicationId, Guid emailId, Guid userId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetMainEmail"), emailId, userId);
        }

        public static List<PhoneNumber> get_phone_numbers(Guid? applicationId, Guid userId)
        {
            return USRParsers.phone_numbers(DBConnector.read(applicationId, GetFullyQualifiedName("GetPhoneNumbers"), userId));
        }

        public static PhoneNumber get_phone_number(Guid? applicationId, Guid numberId)
        {
            return USRParsers.phone_numbers(
                DBConnector.read(applicationId, GetFullyQualifiedName("GetPhoneNumber"), numberId)).FirstOrDefault();
        }

        public static Guid? get_main_phone(Guid? applicationId, Guid userId)
        {
            return DBConnector.get_guid(applicationId, GetFullyQualifiedName("GetMainPhone"), userId);
        }

        public static List<EmailAddress> get_email_addresses(Guid? applicationId, Guid userId)
        {
            return USRParsers.email_addresses(DBConnector.read(applicationId, GetFullyQualifiedName("GetEmailAddresses"), userId));
        }

        public static EmailAddress get_email_address(Guid? applicationId, Guid emailId)
        {
            return USRParsers.email_addresses(
                DBConnector.read(applicationId, GetFullyQualifiedName("GetEmailAddress"), emailId)).FirstOrDefault();
        }

        public static List<string> get_not_existing_emails(Guid applicationId, List<string> emails)
        {
            if (emails == null) emails = new List<string>();

            DBCompositeType<StringTableType> emailsParam = new DBCompositeType<StringTableType>()
                .add(emails.Select(e => new StringTableType(e)).ToList());

            return DBConnector.get_string_list(applicationId, GetFullyQualifiedName("GetNotExistingEmails"), applicationId, emailsParam);
        }

        public static bool email_exists(Guid applicationId, string email)
        {
            return get_not_existing_emails(applicationId, new List<string>() { email }).Count == 0;
        }

        public static List<EmailAddress> get_email_owners(Guid? applicationId, List<string> emails)
        {
            return USRParsers.email_addresses(DBConnector.read(applicationId, GetFullyQualifiedName("GetEmailOwners"),
                string.Join(",", emails), ','));
        }

        public static List<PhoneNumber> get_phone_owners(Guid? applicationId, List<string> numbers)
        {
            return USRParsers.phone_numbers(DBConnector.read(applicationId, GetFullyQualifiedName("GetPhoneOwners"),
                string.Join(",", numbers), ','));
        }

        public static Guid? get_main_email(Guid? applicationId, Guid userId)
        {
            return DBConnector.get_guid(applicationId, GetFullyQualifiedName("GetMainEmail"), userId);
        }

        public static List<PhoneNumber> get_users_main_phone(Guid? applicationId, List<Guid> userIds)
        {
            return USRParsers.phone_numbers(DBConnector.read(applicationId, GetFullyQualifiedName("GetUsersMainPhone"),
                ProviderUtil.list_to_string<Guid>(userIds), ','));
        }

        public static List<EmailAddress> get_users_main_email(Guid? applicationId, List<Guid> userIds)
        {
            return USRParsers.email_addresses(DBConnector.read(applicationId, GetFullyQualifiedName("GetUsersMainEmail"),
                ProviderUtil.list_to_string<Guid>(userIds), ','));
        }

        public static List<JobExperience> get_job_experiences(Guid applicationId, Guid userId)
        {
            return USRParsers.job_experiences(DBConnector.read(applicationId, GetFullyQualifiedName("GetJobExperiences"),
                applicationId, userId));
        }

        public static JobExperience get_job_experience(Guid applicationId, Guid id)
        {
            return USRParsers.job_experiences(DBConnector.read(applicationId, GetFullyQualifiedName("GetJobExperience"),
                applicationId, id)).FirstOrDefault();
        }

        public static List<EducationalExperience> get_educational_experiences(Guid applicationId, Guid userId)
        {
            return USRParsers.educational_experiences(DBConnector.read(applicationId, GetFullyQualifiedName("GetEducationalExperiences"),
                applicationId, userId));
        }

        public static EducationalExperience get_educational_experience(Guid applicationId, Guid id)
        {
            return USRParsers.educational_experiences(DBConnector.read(applicationId, GetFullyQualifiedName("GetEducationalExperience"),
                applicationId, id)).FirstOrDefault();
        }

        public static List<HonorsAndAwards> get_honors_and_awards(Guid applicationId, Guid userId)
        {
            return USRParsers.honors_and_awards(DBConnector.read(applicationId, GetFullyQualifiedName("GetHonorsAndAwards"),
                applicationId, userId));
        }

        public static HonorsAndAwards get_honor_or_award(Guid applicationId, Guid id)
        {
            return USRParsers.honors_and_awards(DBConnector.read(applicationId, GetFullyQualifiedName("GetHonorOrAward"),
                applicationId, id)).FirstOrDefault();
        }

        public static List<Language> get_user_languages(Guid applicationId, Guid userId)
        {
            DBResultSet results = DBConnector.read(applicationId, GetFullyQualifiedName("GetUserLanguages"), applicationId, userId);
            return USRParsers.languages(results, isUserLanguage: true);
        }

        public static Language get_user_language(Guid applicationId, Guid id)
        {
            DBResultSet results = DBConnector.read(applicationId, GetFullyQualifiedName("GetUserLanguage"), applicationId, id);
            return USRParsers.languages(results, isUserLanguage: true).FirstOrDefault();
        }

        public static List<Language> get_languages(Guid applicationId)
        {
            DBResultSet results = DBConnector.read(applicationId, GetFullyQualifiedName("GetLanguages"), applicationId, null, null);
            return USRParsers.languages(results, isUserLanguage: false);
        }

        public static bool set_job_experience(Guid applicationId, Guid jobId, Guid userId, Guid currentUserId,
            string title, string employer, DateTime? startDate, DateTime? endDate)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetJobExperience"),
                applicationId, jobId, userId, currentUserId, DateTime.Now, title, employer, startDate, endDate);
        }

        public static bool set_educational_experience(Guid applicationId, Guid educationId, Guid userId, 
            Guid currentUserId, string school, string studyField, EducationalLevel? degree, GraduateDegree? level, 
            DateTime? startDate, DateTime? endDate, bool isSchool)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetEducationalExperience"),
                applicationId, educationId, userId, currentUserId, DateTime.Now, school, studyField,
                degree.ToString(), level.ToString(), startDate, endDate, isSchool);
        }

        public static bool set_honor_and_award(Guid applicationId, Guid honorId, Guid userId, Guid currentUserId,
            string title, string occupation, string issuer, DateTime? issueDate, string description)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetHonorAndAward"),
                applicationId, honorId, userId, currentUserId, DateTime.Now, title, occupation, issuer, issueDate, description);
        }

        public static bool set_language(Guid applicationId, 
            Guid Id, string languageName, Guid userId, Guid currentUserId, LanguageLevel langLevel)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetLanguage"),
                applicationId, Id, languageName, userId, currentUserId, DateTime.Now, langLevel.ToString());
        }

        public static bool remove_job_experience(Guid applicationId, Guid jobId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("RemoveJobExperience"), applicationId, jobId);
        }

        public static bool remove_education_experience(Guid applicationId, Guid educationId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("RemoveEducationalExperience"), applicationId, educationId);
        }

        public static bool remove_honor_and_award(Guid applicationId, Guid honorId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("RemoveHonorAndAward"), applicationId, honorId);
        }

        public static bool remove_language(Guid applicationId, Guid languageId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("RemoveLanguage"), applicationId, languageId);
        }

        /* end of Profile */

        /* User Groups */

        public static bool create_user_group(Guid applicationId, Guid groupId,
            string title, string description, Guid currentUserId)
        {
            if (!string.IsNullOrEmpty(title)) title = title.Trim();
            if (!string.IsNullOrEmpty(description)) description = description.Trim();

            if (string.IsNullOrEmpty(title)) return false;

            return DBConnector.succeed(applicationId, GetFullyQualifiedName("CreateUserGroup"),
                applicationId, groupId, title, description, currentUserId, DateTime.Now);
        }

        public static bool modify_user_group(Guid applicationId, Guid groupId,
            string title, string description, Guid currentUserId)
        {
            if (!string.IsNullOrEmpty(title)) title = title.Trim();
            if (!string.IsNullOrEmpty(description)) description = description.Trim();

            if (string.IsNullOrEmpty(title)) return false;

            return DBConnector.succeed(applicationId, GetFullyQualifiedName("ModifyUserGroup"),
                applicationId, groupId, title, description, currentUserId, DateTime.Now);
        }

        public static bool remove_user_group(Guid applicationId, Guid groupId, Guid currentUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("RemoveUserGroup"),
                applicationId, groupId, currentUserId, DateTime.Now);
        }

        public static bool add_user_group_members(Guid applicationId, Guid groupId, List<Guid> userIds, Guid currentUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("AddUserGroupMembers"),
                applicationId, groupId, ProviderUtil.list_to_string<Guid>(userIds), ',', currentUserId, DateTime.Now);
        }

        public static bool add_user_group_member(Guid applicationId, Guid groupId, Guid userId, Guid currentUserId)
        {
            return add_user_group_members(applicationId, groupId, new List<Guid>() { userId }, currentUserId);
        }

        public static bool remove_user_group_members(Guid applicationId, Guid groupId, 
            List<Guid> userIds, Guid currentUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("RemoveUserGroupMembers"),
                applicationId, groupId, ProviderUtil.list_to_string<Guid>(userIds), ',', currentUserId, DateTime.Now);
        }

        public static bool remove_user_group_member(Guid applicationId, Guid groupId, Guid userId, Guid currentUserId)
        {
            return remove_user_group_members(applicationId, groupId, new List<Guid>() { userId }, currentUserId);
        }

        public static bool set_user_group_permission(Guid applicationId, Guid groupId, Guid roleId, Guid currentUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("SetUserGroupPermission"),
                applicationId, groupId, roleId, currentUserId, DateTime.Now);
        }

        public static bool unset_user_group_permission(Guid applicationId, Guid groupId, Guid roleId, Guid currentUserId)
        {
            return DBConnector.succeed(applicationId, GetFullyQualifiedName("UnsetUserGroupPermission"),
                applicationId, groupId, roleId, currentUserId, DateTime.Now);
        }

        public static List<UserGroup> get_user_groups(Guid applicationId, List<Guid> groupIds)
        {
            return USRParsers.user_groups(DBConnector.read(applicationId, GetFullyQualifiedName("GetUserGroups"),
                applicationId, ProviderUtil.list_to_string<Guid>(groupIds), ','));
        }

        public static List<UserGroup> get_user_groups(Guid applicationId)
        {
            return get_user_groups(applicationId, new List<Guid>());
        }

        public static UserGroup get_user_group(Guid applicationId, Guid groupId)
        {
            return get_user_groups(applicationId, new List<Guid>() { groupId }).FirstOrDefault();
        }

        public static List<User> get_user_group_members(Guid applicationId, Guid groupId)
        {
            return USRParsers.users(DBConnector.read(applicationId, GetFullyQualifiedName("GetUserGroupMembers"), applicationId, groupId));
        }

        public static List<AccessRole> get_user_group_access_roles(Guid applicationId, Guid groupId)
        {
            return USRParsers.access_roles(DBConnector.read(applicationId, GetFullyQualifiedName("GetUserGroupAccessRoles"),
                applicationId, groupId));
        }

        public static List<AccessRoleName> check_user_group_permissions(Guid applicationId, Guid userId, 
            List<AccessRoleName> permissions)
        {
            if (permissions == null) permissions = new List<AccessRoleName>();

            DBCompositeType<StringTableType> permissionsParam = new DBCompositeType<StringTableType>()
                .add(permissions.Where(p => p != AccessRoleName.None).Select(p => new StringTableType(p.ToString())).ToList());

            return USRParsers.permissions(DBConnector.read(applicationId, GetFullyQualifiedName("CheckUserGroupPermissions"),
                applicationId, userId, permissionsParam));
        }

        public static List<AccessRole> get_access_roles(Guid applicationId)
        {
            return USRParsers.access_roles(DBConnector.read(applicationId, GetFullyQualifiedName("GetAccessRoles"), applicationId));
        }

        /* end of User Groups */
    }
}