//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaaiVanIntermediate.RaaiVanCoreNetwork {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RaaiVanCoreNetwork.CoreNetworkSoap")]
    public interface CoreNetworkSoap {
        
        // CODEGEN: Generating message contract since element name nodeTypeId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNodeType", ReplyAction="*")]
        RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeTypeResponse AddNodeType(RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeTypeRequest request);
        
        // CODEGEN: Generating message contract since element name nodeId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNode", ReplyAction="*")]
        RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeResponse AddNode(RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeRequest request);
        
        // CODEGEN: Generating message contract since element name nodeId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyNode", ReplyAction="*")]
        RaaiVanIntermediate.RaaiVanCoreNetwork.ModifyNodeResponse ModifyNode(RaaiVanIntermediate.RaaiVanCoreNetwork.ModifyNodeRequest request);
        
        // CODEGEN: Generating message contract since element name nodeId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoveNode", ReplyAction="*")]
        RaaiVanIntermediate.RaaiVanCoreNetwork.MoveNodeResponse MoveNode(RaaiVanIntermediate.RaaiVanCoreNetwork.MoveNodeRequest request);
        
        // CODEGEN: Generating message contract since element name nodeId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMember", ReplyAction="*")]
        RaaiVanIntermediate.RaaiVanCoreNetwork.AddMemberResponse AddMember(RaaiVanIntermediate.RaaiVanCoreNetwork.AddMemberRequest request);
        
        // CODEGEN: Generating message contract since element name nodeId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveMember", ReplyAction="*")]
        RaaiVanIntermediate.RaaiVanCoreNetwork.RemoveMemberResponse RemoveMember(RaaiVanIntermediate.RaaiVanCoreNetwork.RemoveMemberRequest request);
        
        // CODEGEN: Generating message contract since element name nodeId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAdmin", ReplyAction="*")]
        RaaiVanIntermediate.RaaiVanCoreNetwork.SetAdminResponse SetAdmin(RaaiVanIntermediate.RaaiVanCoreNetwork.SetAdminRequest request);
        
        // CODEGEN: Generating message contract since element name nodeId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnsetAdmin", ReplyAction="*")]
        RaaiVanIntermediate.RaaiVanCoreNetwork.UnsetAdminResponse UnsetAdmin(RaaiVanIntermediate.RaaiVanCoreNetwork.UnsetAdminRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNodeTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNodeType", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeTypeRequestBody Body;
        
        public AddNodeTypeRequest() {
        }
        
        public AddNodeTypeRequest(RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNodeTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nodeTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string typeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        public AddNodeTypeRequestBody() {
        }
        
        public AddNodeTypeRequestBody(string nodeTypeId, string typeName, string description) {
            this.nodeTypeId = nodeTypeId;
            this.typeName = typeName;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNodeTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNodeTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeTypeResponseBody Body;
        
        public AddNodeTypeResponse() {
        }
        
        public AddNodeTypeResponse(RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNodeTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddNodeTypeResult;
        
        public AddNodeTypeResponseBody() {
        }
        
        public AddNodeTypeResponseBody(bool AddNodeTypeResult) {
            this.AddNodeTypeResult = AddNodeTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNode", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeRequestBody Body;
        
        public AddNodeRequest() {
        }
        
        public AddNodeRequest(RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nodeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nodeTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string parentNodeId;
        
        public AddNodeRequestBody() {
        }
        
        public AddNodeRequestBody(string nodeId, string nodeTypeId, string name, string description, string parentNodeId) {
            this.nodeId = nodeId;
            this.nodeTypeId = nodeTypeId;
            this.name = name;
            this.description = description;
            this.parentNodeId = parentNodeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeResponseBody Body;
        
        public AddNodeResponse() {
        }
        
        public AddNodeResponse(RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddNodeResult;
        
        public AddNodeResponseBody() {
        }
        
        public AddNodeResponseBody(bool AddNodeResult) {
            this.AddNodeResult = AddNodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyNodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyNode", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.ModifyNodeRequestBody Body;
        
        public ModifyNodeRequest() {
        }
        
        public ModifyNodeRequest(RaaiVanIntermediate.RaaiVanCoreNetwork.ModifyNodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifyNodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nodeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nodeTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string description;
        
        public ModifyNodeRequestBody() {
        }
        
        public ModifyNodeRequestBody(string nodeId, string nodeTypeId, string name, string description) {
            this.nodeId = nodeId;
            this.nodeTypeId = nodeTypeId;
            this.name = name;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyNodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyNodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.ModifyNodeResponseBody Body;
        
        public ModifyNodeResponse() {
        }
        
        public ModifyNodeResponse(RaaiVanIntermediate.RaaiVanCoreNetwork.ModifyNodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifyNodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ModifyNodeResult;
        
        public ModifyNodeResponseBody() {
        }
        
        public ModifyNodeResponseBody(bool ModifyNodeResult) {
            this.ModifyNodeResult = ModifyNodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveNodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveNode", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.MoveNodeRequestBody Body;
        
        public MoveNodeRequest() {
        }
        
        public MoveNodeRequest(RaaiVanIntermediate.RaaiVanCoreNetwork.MoveNodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MoveNodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nodeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parentNodeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nodeTypeId;
        
        public MoveNodeRequestBody() {
        }
        
        public MoveNodeRequestBody(string nodeId, string parentNodeId, string nodeTypeId) {
            this.nodeId = nodeId;
            this.parentNodeId = parentNodeId;
            this.nodeTypeId = nodeTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveNodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveNodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.MoveNodeResponseBody Body;
        
        public MoveNodeResponse() {
        }
        
        public MoveNodeResponse(RaaiVanIntermediate.RaaiVanCoreNetwork.MoveNodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MoveNodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MoveNodeResult;
        
        public MoveNodeResponseBody() {
        }
        
        public MoveNodeResponseBody(bool MoveNodeResult) {
            this.MoveNodeResult = MoveNodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMember", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.AddMemberRequestBody Body;
        
        public AddMemberRequest() {
        }
        
        public AddMemberRequest(RaaiVanIntermediate.RaaiVanCoreNetwork.AddMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nodeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nodeTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        public AddMemberRequestBody() {
        }
        
        public AddMemberRequestBody(string nodeId, string nodeTypeId, string username) {
            this.nodeId = nodeId;
            this.nodeTypeId = nodeTypeId;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMemberResponse", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.AddMemberResponseBody Body;
        
        public AddMemberResponse() {
        }
        
        public AddMemberResponse(RaaiVanIntermediate.RaaiVanCoreNetwork.AddMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMemberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddMemberResult;
        
        public AddMemberResponseBody() {
        }
        
        public AddMemberResponseBody(bool AddMemberResult) {
            this.AddMemberResult = AddMemberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveMemberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveMember", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.RemoveMemberRequestBody Body;
        
        public RemoveMemberRequest() {
        }
        
        public RemoveMemberRequest(RaaiVanIntermediate.RaaiVanCoreNetwork.RemoveMemberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveMemberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nodeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nodeTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        public RemoveMemberRequestBody() {
        }
        
        public RemoveMemberRequestBody(string nodeId, string nodeTypeId, string username) {
            this.nodeId = nodeId;
            this.nodeTypeId = nodeTypeId;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveMemberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveMemberResponse", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.RemoveMemberResponseBody Body;
        
        public RemoveMemberResponse() {
        }
        
        public RemoveMemberResponse(RaaiVanIntermediate.RaaiVanCoreNetwork.RemoveMemberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveMemberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RemoveMemberResult;
        
        public RemoveMemberResponseBody() {
        }
        
        public RemoveMemberResponseBody(bool RemoveMemberResult) {
            this.RemoveMemberResult = RemoveMemberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAdmin", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.SetAdminRequestBody Body;
        
        public SetAdminRequest() {
        }
        
        public SetAdminRequest(RaaiVanIntermediate.RaaiVanCoreNetwork.SetAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nodeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nodeTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        public SetAdminRequestBody() {
        }
        
        public SetAdminRequestBody(string nodeId, string nodeTypeId, string username) {
            this.nodeId = nodeId;
            this.nodeTypeId = nodeTypeId;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.SetAdminResponseBody Body;
        
        public SetAdminResponse() {
        }
        
        public SetAdminResponse(RaaiVanIntermediate.RaaiVanCoreNetwork.SetAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetAdminResult;
        
        public SetAdminResponseBody() {
        }
        
        public SetAdminResponseBody(bool SetAdminResult) {
            this.SetAdminResult = SetAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnsetAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnsetAdmin", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.UnsetAdminRequestBody Body;
        
        public UnsetAdminRequest() {
        }
        
        public UnsetAdminRequest(RaaiVanIntermediate.RaaiVanCoreNetwork.UnsetAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnsetAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nodeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nodeTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        public UnsetAdminRequestBody() {
        }
        
        public UnsetAdminRequestBody(string nodeId, string nodeTypeId, string username) {
            this.nodeId = nodeId;
            this.nodeTypeId = nodeTypeId;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnsetAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnsetAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public RaaiVanIntermediate.RaaiVanCoreNetwork.UnsetAdminResponseBody Body;
        
        public UnsetAdminResponse() {
        }
        
        public UnsetAdminResponse(RaaiVanIntermediate.RaaiVanCoreNetwork.UnsetAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnsetAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UnsetAdminResult;
        
        public UnsetAdminResponseBody() {
        }
        
        public UnsetAdminResponseBody(bool UnsetAdminResult) {
            this.UnsetAdminResult = UnsetAdminResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CoreNetworkSoapChannel : RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreNetworkSoapClient : System.ServiceModel.ClientBase<RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap>, RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap {
        
        public CoreNetworkSoapClient() {
        }
        
        public CoreNetworkSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoreNetworkSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreNetworkSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreNetworkSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeTypeResponse RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap.AddNodeType(RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeTypeRequest request) {
            return base.Channel.AddNodeType(request);
        }
        
        public bool AddNodeType(string nodeTypeId, string typeName, string description) {
            RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeTypeRequest inValue = new RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeTypeRequest();
            inValue.Body = new RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeTypeRequestBody();
            inValue.Body.nodeTypeId = nodeTypeId;
            inValue.Body.typeName = typeName;
            inValue.Body.description = description;
            RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeTypeResponse retVal = ((RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap)(this)).AddNodeType(inValue);
            return retVal.Body.AddNodeTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeResponse RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap.AddNode(RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeRequest request) {
            return base.Channel.AddNode(request);
        }
        
        public bool AddNode(string nodeId, string nodeTypeId, string name, string description, string parentNodeId) {
            RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeRequest inValue = new RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeRequest();
            inValue.Body = new RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeRequestBody();
            inValue.Body.nodeId = nodeId;
            inValue.Body.nodeTypeId = nodeTypeId;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.parentNodeId = parentNodeId;
            RaaiVanIntermediate.RaaiVanCoreNetwork.AddNodeResponse retVal = ((RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap)(this)).AddNode(inValue);
            return retVal.Body.AddNodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RaaiVanIntermediate.RaaiVanCoreNetwork.ModifyNodeResponse RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap.ModifyNode(RaaiVanIntermediate.RaaiVanCoreNetwork.ModifyNodeRequest request) {
            return base.Channel.ModifyNode(request);
        }
        
        public bool ModifyNode(string nodeId, string nodeTypeId, string name, string description) {
            RaaiVanIntermediate.RaaiVanCoreNetwork.ModifyNodeRequest inValue = new RaaiVanIntermediate.RaaiVanCoreNetwork.ModifyNodeRequest();
            inValue.Body = new RaaiVanIntermediate.RaaiVanCoreNetwork.ModifyNodeRequestBody();
            inValue.Body.nodeId = nodeId;
            inValue.Body.nodeTypeId = nodeTypeId;
            inValue.Body.name = name;
            inValue.Body.description = description;
            RaaiVanIntermediate.RaaiVanCoreNetwork.ModifyNodeResponse retVal = ((RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap)(this)).ModifyNode(inValue);
            return retVal.Body.ModifyNodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RaaiVanIntermediate.RaaiVanCoreNetwork.MoveNodeResponse RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap.MoveNode(RaaiVanIntermediate.RaaiVanCoreNetwork.MoveNodeRequest request) {
            return base.Channel.MoveNode(request);
        }
        
        public bool MoveNode(string nodeId, string parentNodeId, string nodeTypeId) {
            RaaiVanIntermediate.RaaiVanCoreNetwork.MoveNodeRequest inValue = new RaaiVanIntermediate.RaaiVanCoreNetwork.MoveNodeRequest();
            inValue.Body = new RaaiVanIntermediate.RaaiVanCoreNetwork.MoveNodeRequestBody();
            inValue.Body.nodeId = nodeId;
            inValue.Body.parentNodeId = parentNodeId;
            inValue.Body.nodeTypeId = nodeTypeId;
            RaaiVanIntermediate.RaaiVanCoreNetwork.MoveNodeResponse retVal = ((RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap)(this)).MoveNode(inValue);
            return retVal.Body.MoveNodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RaaiVanIntermediate.RaaiVanCoreNetwork.AddMemberResponse RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap.AddMember(RaaiVanIntermediate.RaaiVanCoreNetwork.AddMemberRequest request) {
            return base.Channel.AddMember(request);
        }
        
        public bool AddMember(string nodeId, string nodeTypeId, string username) {
            RaaiVanIntermediate.RaaiVanCoreNetwork.AddMemberRequest inValue = new RaaiVanIntermediate.RaaiVanCoreNetwork.AddMemberRequest();
            inValue.Body = new RaaiVanIntermediate.RaaiVanCoreNetwork.AddMemberRequestBody();
            inValue.Body.nodeId = nodeId;
            inValue.Body.nodeTypeId = nodeTypeId;
            inValue.Body.username = username;
            RaaiVanIntermediate.RaaiVanCoreNetwork.AddMemberResponse retVal = ((RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap)(this)).AddMember(inValue);
            return retVal.Body.AddMemberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RaaiVanIntermediate.RaaiVanCoreNetwork.RemoveMemberResponse RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap.RemoveMember(RaaiVanIntermediate.RaaiVanCoreNetwork.RemoveMemberRequest request) {
            return base.Channel.RemoveMember(request);
        }
        
        public bool RemoveMember(string nodeId, string nodeTypeId, string username) {
            RaaiVanIntermediate.RaaiVanCoreNetwork.RemoveMemberRequest inValue = new RaaiVanIntermediate.RaaiVanCoreNetwork.RemoveMemberRequest();
            inValue.Body = new RaaiVanIntermediate.RaaiVanCoreNetwork.RemoveMemberRequestBody();
            inValue.Body.nodeId = nodeId;
            inValue.Body.nodeTypeId = nodeTypeId;
            inValue.Body.username = username;
            RaaiVanIntermediate.RaaiVanCoreNetwork.RemoveMemberResponse retVal = ((RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap)(this)).RemoveMember(inValue);
            return retVal.Body.RemoveMemberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RaaiVanIntermediate.RaaiVanCoreNetwork.SetAdminResponse RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap.SetAdmin(RaaiVanIntermediate.RaaiVanCoreNetwork.SetAdminRequest request) {
            return base.Channel.SetAdmin(request);
        }
        
        public bool SetAdmin(string nodeId, string nodeTypeId, string username) {
            RaaiVanIntermediate.RaaiVanCoreNetwork.SetAdminRequest inValue = new RaaiVanIntermediate.RaaiVanCoreNetwork.SetAdminRequest();
            inValue.Body = new RaaiVanIntermediate.RaaiVanCoreNetwork.SetAdminRequestBody();
            inValue.Body.nodeId = nodeId;
            inValue.Body.nodeTypeId = nodeTypeId;
            inValue.Body.username = username;
            RaaiVanIntermediate.RaaiVanCoreNetwork.SetAdminResponse retVal = ((RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap)(this)).SetAdmin(inValue);
            return retVal.Body.SetAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RaaiVanIntermediate.RaaiVanCoreNetwork.UnsetAdminResponse RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap.UnsetAdmin(RaaiVanIntermediate.RaaiVanCoreNetwork.UnsetAdminRequest request) {
            return base.Channel.UnsetAdmin(request);
        }
        
        public bool UnsetAdmin(string nodeId, string nodeTypeId, string username) {
            RaaiVanIntermediate.RaaiVanCoreNetwork.UnsetAdminRequest inValue = new RaaiVanIntermediate.RaaiVanCoreNetwork.UnsetAdminRequest();
            inValue.Body = new RaaiVanIntermediate.RaaiVanCoreNetwork.UnsetAdminRequestBody();
            inValue.Body.nodeId = nodeId;
            inValue.Body.nodeTypeId = nodeTypeId;
            inValue.Body.username = username;
            RaaiVanIntermediate.RaaiVanCoreNetwork.UnsetAdminResponse retVal = ((RaaiVanIntermediate.RaaiVanCoreNetwork.CoreNetworkSoap)(this)).UnsetAdmin(inValue);
            return retVal.Body.UnsetAdminResult;
        }
    }
}
