USE [EKM_App]
GO


CREATE TABLE [dbo].[USR_PasswordsHistory](
	[ID]		[bigint] NOT NULL IDENTITY(1, 1),
	[UserID]	[uniqueidentifier] NOT NULL,
	[Password]	[nvarchar] (256) NOT NULL,
	[SetDate]	[datetime] NOT NULL
CONSTRAINT [PK_USR_PasswordsHistory] PRIMARY KEY CLUSTERED
(
	[ID] ASC 
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USR_PasswordsHistory] ADD  CONSTRAINT [UK_USR_PasswordsHistory] UNIQUE NONCLUSTERED 
(
	[UserID]	ASC,
	[ID]		ASC,
	[Password]	ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



INSERT INTO [dbo].[USR_PasswordsHistory](UserID, [Password], SetDate)
SELECT UserId, [Password], CreateDate
FROM [dbo].[aspnet_Membership]

GO





SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


CREATE TABLE [dbo].[LG_ErrorLogs](
	[LogID] [bigint] IDENTITY(1,1) NOT NULL,
	[UserID] [uniqueidentifier] NULL,
	[Subject] [varchar](1000) NOT NULL,
	[Description] [nvarchar](2000) NULL,
	[Date] [datetime] NOT NULL,
	[ModuleIdentifier] [varchar](20) NULL
 CONSTRAINT [PK_LG_ErrorLogs] PRIMARY KEY CLUSTERED 
(
	[LogID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO




SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



UPDATE [dbo].[AppSetting]
	SET [Version] = 'v27.0.5.0' -- 13941105
GO

