USE [EKM_App]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	SET ANSI_PADDING ON
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	ALTER TABLE [dbo].[LG_Logs]
	ADD [Level] [varchar](20) NULL
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	SET ANSI_PADDING OFF
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	SET ANSI_PADDING ON
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	ALTER TABLE [dbo].[LG_ErrorLogs]
	ADD [Level] [varchar](20) NULL
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	SET ANSI_PADDING OFF
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	SET ANSI_PADDING ON
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	ALTER TABLE [dbo].[CN_Services]
	ADD [UniqueMembership] [bit] NULL
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	SET ANSI_PADDING OFF
END
GO


IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	ALTER TABLE [dbo].[FG_ExtendedFormElements]
	DROP COLUMN IsUnique
END
GO


IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	DECLARE @Items TABLE ([Action] varchar(100), [Level] varchar(20))

	INSERT INTO @Items ([Action], [Level])
	VALUES	(N'Node_AccessDenied', N'Error'),
			(N'PendingMembers_AccessDenied', N'Error'),
			(N'AddNodeType', N'Trace'),
			(N'AddNodeType_PermissionFailed', N'Error'),
			(N'RenameNodeType', N'Trace'),
			(N'RenameNodeType_PermissionFailed', N'Error'),
			(N'ChangeNodeType', N'Trace'),
			(N'ChangeNodeType_PermissionFailed', N'Error'),
			(N'SetNodeTypeAdditionalID', N'Trace'),
			(N'SetNodeTypeAdditionalID_PermissionFailed', N'Error'),
			(N'SetNodeTypeAdditionalIDPattern', N'Trace'),
			(N'SetNodeTypeAdditionalIDPattern_PermissionFailed', N'Error'),
			(N'MoveNodeType', N'Trace'),
			(N'MoveNodeType_PermissionFailed', N'Error'),
			(N'RemoveNodeType', N'Trace'),
			(N'RemoveNodeType_PermissionFailed', N'Error'),
			(N'RecoverNodeType', N'Trace'),
			(N'RecoverNodeType_PermissionFailed', N'Error'),
			(N'AddRelationType', N'Trace'),
			(N'AddRelationType_PermissionFailed', N'Error'),
			(N'ModifyRelationType', N'Trace'),
			(N'ModifyRelationType_PermissionFailed', N'Error'),
			(N'RemoveRelationType', N'Trace'),
			(N'RemoveRelationType_PermissionFailed', N'Error'),
			(N'AddNode', N'Trace'),
			(N'AddNode_PermissionFailed', N'Error'),
			(N'ModifyNode', N'Trace'),
			(N'ModifyNode_PermissionFailed', N'Error'),
			(N'SetDocumentTreeNodeID', N'Trace'),
			(N'SetDocumentTreeNodeID_PermissionFailed', N'Error'),
			(N'ModifyNodeName', N'Trace'),
			(N'ModifyNodeName_PermissionFailed', N'Error'),
			(N'ModifyNodeDescription', N'Trace'),
			(N'ModifyNodeDescription_PermissionFailed', N'Error'),
			(N'ModifyNodePublicDescription', N'Trace'),
			(N'ModifyNodePublicDescription_PermissionFailed', N'Error'),
			(N'SetNodeExpirationDate', N'Trace'),
			(N'SetNodeExpirationDate_PermissionFailed', N'Error'),
			(N'SetPreviousVersion', N'Trace'),
			(N'SetPreviousVersion_PermissionFailed', N'Error'),
			(N'ModifyNodeTags', N'Trace'),
			(N'ModifyNodeTags_PermissionFailed', N'Error'),
			(N'SetNodeSearchability', N'Trace'),
			(N'SetNodeSearchability_PermissionFailed', N'Error'),
			(N'RemoveNode', N'Trace'),
			(N'RemoveNode_PermissionFailed', N'Error'),
			(N'RecycleNode', N'Trace'),
			(N'RecycleNode_PermissionFailed', N'Error'),
			(N'SortNodeTypes', N'Trace'),
			(N'SortNodeTypes_PermissionFailed', N'Error'),
			(N'SortNodes', N'Trace'),
			(N'SortNodes_PermissionFailed', N'Error'),
			(N'SetNodeDirectParent', N'Trace'),
			(N'SetNodeDirectParent_PermissionFailed', N'Error'),
			(N'AddNodeRelation', N'Trace'),
			(N'AddNodeRelation_PermissionFailed', N'Error'),
			(N'SaveRelations', N'Trace'),
			(N'SaveRelations_PermissionFailed', N'Error'),
			(N'RemoveNodeRelation', N'Trace'),
			(N'RemoveNodeRelation_PermissionFailed', N'Error'),
			(N'AddComplex', N'Trace'),
			(N'AddComplex_PermissionFailed', N'Error'),
			(N'ModifyComplex', N'Trace'),
			(N'ModifyComplex_PermissionFailed', N'Error'),
			(N'RemoveComplex', N'Trace'),
			(N'RemoveComplex_PermissionFailed', N'Error'),
			(N'AddNodeToComplex', N'Trace'),
			(N'AddNodeToComplex_PermissionFailed', N'Error'),
			(N'RemoveComplexNode', N'Trace'),
			(N'RemoveComplexNode_PermissionFailed', N'Error'),
			(N'AddComplexAdmin', N'Trace'),
			(N'AddComplexAdmin_PermissionFailed', N'Error'),
			(N'RemoveComplexAdmin', N'Trace'),
			(N'RemoveComplexAdmin_PermissionFailed', N'Error'),
			(N'LikeNode', N'Trace'),
			(N'UnlikeNode', N'Trace'),
			(N'AddNodeMember', N'Trace'),
			(N'AddNodeMember_PermissionFailed', N'Error'),
			(N'RemoveNodeMember', N'Trace'),
			(N'RemoveNodeMember_PermissionFailed', N'Error'),
			(N'AcceptNodeMember', N'Trace'),
			(N'AcceptNodeMember_PermissionFailed', N'Error'),
			(N'SetUserAsNodeAdmin', N'Trace'),
			(N'SetUserAsNodeAdmin_PermissionFailed', N'Error'),
			(N'RemoveNodeAdmin', N'Trace'),
			(N'RemoveNodeAdmin_PermissionFailed', N'Error'),
			(N'AddExpert', N'Trace'),
			(N'AddExpert_PermissionFailed', N'Error'),
			(N'RemoveExpert', N'Trace'),
			(N'RemoveExpert_PermissionFailed', N'Error'),
			(N'EnableExtension', N'Trace'),
			(N'EnableExtension_PermissionFailed', N'Error'),
			(N'DisableExtension', N'Trace'),
			(N'DisableExtension_PermissionFailed', N'Error'),
			(N'SetExtensionTitle', N'Trace'),
			(N'SetExtensionTitle_PermissionFailed', N'Error'),
			(N'MoveExtension', N'Trace'),
			(N'MoveExtension_PermissionFailed', N'Error'),
			(N'SetServiceTitle', N'Trace'),
			(N'SetServiceTitle_PermissionFailed', N'Error'),
			(N'SetServiceDescription', N'Trace'),
			(N'SetServiceDescription_PermissionFailed', N'Error'),
			(N'SetServiceSuccessMessage', N'Trace'),
			(N'SetServiceSuccessMessage_PermissionFailed', N'Error'),
			(N'SetServiceAdminType', N'Trace'),
			(N'SetServiceAdminType_PermissionFailed', N'Error'),
			(N'SetServiceMaxAcceptableAdminLevel', N'Trace'),
			(N'SetServiceMaxAcceptableAdminLevel_PermissionFailed', N'Error'),
			(N'SetContributionLimits', N'Trace'),
			(N'SetContributionLimits_PermissionFailed', N'Error'),
			(N'SetServiceEnableContribution', N'Trace'),
			(N'SetServiceEnableContribution_PermissionFailed', N'Error'),
			(N'SetServiceNoContent', N'Trace'),
			(N'SetServiceNoContent_PermissionFailed', N'Error'),
			(N'SetServiceIsDocument', N'Trace'),
			(N'SetServiceIsDocument_PermissionFailed', N'Error'),
			(N'SetServiceIsKnowledge', N'Trace'),
			(N'SetServiceIsKnowledge_PermissionFailed', N'Error'),
			(N'SetServiceIsTree', N'Trace'),
			(N'SetServiceIsTree_PermissionFailed', N'Error'),
			(N'SetServiceEditableForAdmin', N'Trace'),
			(N'SetServiceEditableForAdmin_PermissionFailed', N'Error'),
			(N'SetServiceEditableForCreator', N'Trace'),
			(N'SetServiceEditableForCreator_PermissionFailed', N'Error'),
			(N'SetServiceEditableForOwners', N'Trace'),
			(N'SetServiceEditableForOwners_PermissionFailed', N'Error'),
			(N'SetServiceEditableForExperts', N'Trace'),
			(N'SetServiceEditableForExperts_PermissionFailed', N'Error'),
			(N'SetServiceEditableForMembers', N'Trace'),
			(N'SetServiceEditableForMembers_PermissionFailed', N'Error'),
			(N'SetServiceEditSuggestion', N'Trace'),
			(N'SetServiceEditSuggestion_PermissionFailed', N'Error'),
			(N'AddServiceFreeUser', N'Trace'),
			(N'AddServiceFreeUser_PermissionFailed', N'Error'),
			(N'RemoveServiceFreeUser', N'Trace'),
			(N'RemoveServiceFreeUser_PermissionFailed', N'Error'),
			(N'AddServiceAdmin', N'Trace'),
			(N'AddServiceAdmin_PermissionFailed', N'Error'),
			(N'RemoveServiceAdmin', N'Trace'),
			(N'RemoveServiceAdmin_PermissionFailed', N'Error'),
			(N'SetAdminArea', N'Trace'),
			(N'SetAdminArea_PermissionFailed', N'Error'),
			(N'SetContributors', N'Trace'),
			(N'SetContributors_PermissionFailed', N'Error'),
			(N'CreateDocumentTree', N'Trace'),
			(N'CreateDocumentTree_PermissionFailed', N'Error'),
			(N'ModifyDocumentTree', N'Trace'),
			(N'ModifyDocumentTree_PermissionFailed', N'Error'),
			(N'RemoveDocumentTree', N'Trace'),
			(N'RemoveDocumentTree_PermissionFailed', N'Error'),
			(N'RecycleDocumentTree', N'Trace'),
			(N'RecycleDocumentTree_PermissionFailed', N'Error'),
			(N'CreateDocumentTreeNode', N'Trace'),
			(N'CreateDocumentTreeNode_PermissionFailed', N'Error'),
			(N'ModifyDocumentTreeNodeName', N'Trace'),
			(N'ModifyDocumentTreeNodeName_PermissionFailed', N'Error'),
			(N'MoveDocumentTreeNode', N'Trace'),
			(N'MoveDocumentTreeNode_PermissionFailed', N'Error'),
			(N'RemoveDocumentTreeNode', N'Trace'),
			(N'RemoveDocumentTreeNode_PermissionFailed', N'Error'),
			(N'SortDocumentTreeNodes', N'Trace'),
			(N'SortDocumentTreeNodes_PermissionFailed', N'Error'),
			(N'MoveDocuments', N'Trace'),
			(N'MoveDocuments_PermissionFailed', N'Error'),
			(N'Download_AccessDenied', N'Error'),
			(N'AddOwnerTree', N'Trace'),
			(N'AddOwnerTree_PermissionFailed', N'Error'),
			(N'RemoveOwnerTree', N'Trace'),
			(N'RemoveOwnerTree_PermissionFailed', N'Error'),
			(N'AddTreeNodeContents', N'Trace'),
			(N'AddTreeNodeContents_PermissionFailed', N'Error'),
			(N'RemoveTreeNodeContents', N'Trace'),
			(N'RemoveTreeNodeContents_PermissionFailed', N'Error'),
			(N'RegisterNewEvent', N'Trace'),
			(N'RemoveEventUser', N'Trace'),
			(N'ChangeEventUserStatus', N'Trace'),
			(N'CreateForm', N'Trace'),
			(N'CreateForm_PermissionFailed', N'Error'),
			(N'ModifyFormTitle', N'Trace'),
			(N'ModifyFormTitle_PermissionFailed', N'Error'),
			(N'ModifyFormName', N'Trace'),
			(N'ModifyFormName_PermissionFailed', N'Error'),
			(N'ModifyFormDescription', N'Trace'),
			(N'ModifyFormDescription_PermissionFailed', N'Error'),
			(N'RemoveForm', N'Trace'),
			(N'RemoveForm_PermissionFailed', N'Error'),
			(N'RecycleForm', N'Trace'),
			(N'RecycleForm_PermissionFailed', N'Error'),
			(N'AddFormElement', N'Trace'),
			(N'AddFormElement_PermissionFailed', N'Error'),
			(N'ModifyFormElement', N'Trace'),
			(N'ModifyFormElement_PermissionFailed', N'Error'),
			(N'MoveFormElementUp', N'Trace'),
			(N'MoveFormElementUp_PermissionFailed', N'Error'),
			(N'MoveFormElementDown', N'Trace'),
			(N'MoveFormElementDown_PermissionFailed', N'Error'),
			(N'SetFormElementNecessity', N'Trace'),
			(N'SetFormElementNecessity_PermissionFailed', N'Error'),
			(N'SetFormElementUniqueness', N'Trace'),
			(N'SetFormElementUniqueness_PermissionFailed', N'Error'),
			(N'RemoveFormElement', N'Trace'),
			(N'RemoveFormElement_PermissionFailed', N'Error'),
			(N'CreateFormInstance', N'Trace'),
			(N'RemoveFormInstance', N'Trace'),
			(N'RemoveOwnerFormInstances', N'Trace'),
			(N'ModifyFormInstanceElements', N'Trace'),
			(N'SetFormInstanceAsFilled', N'Trace'),
			(N'SetFormInstanceAsNotFilled', N'Trace'),
			(N'SetFormOwner', N'Trace'),
			(N'RemoveFormOwner', N'Trace'),
			(N'SetElementLimits', N'Trace'),
			(N'SetElementLimitNecessity', N'Trace'),
			(N'RemoveElementLimit', N'Trace'),
			(N'AddPoll', N'Trace'),
			(N'AddPoll_PermissionFailed', N'Error'),
			(N'RenamePoll', N'Trace'),
			(N'RenamePoll_PermissionFailed', N'Error'),
			(N'RemovePoll', N'Trace'),
			(N'RemovePoll_PermissionFailed', N'Error'),
			(N'RecyclePoll', N'Trace'),
			(N'RecyclePoll_PermissionFailed', N'Error'),
			(N'SetPollDescription', N'Trace'),
			(N'SetPollDescription_PermissionFailed', N'Error'),
			(N'SetPollBeginDate', N'Trace'),
			(N'SetPollBeginDate_PermissionFailed', N'Error'),
			(N'SetPollFinishDate', N'Trace'),
			(N'SetPollFinishDate_PermissionFailed', N'Error'),
			(N'SetPollShowSummary', N'Trace'),
			(N'SetPollShowSummary_PermissionFailed', N'Error'),
			(N'SetPollHideContributors', N'Trace'),
			(N'SetPollHideContributors_PermissionFailed', N'Error'),
			(N'AddKnowledgeType', N'Trace'),
			(N'AddKnowledgeType_PermissionFailed', N'Error'),
			(N'RemoveKnowledgeType', N'Trace'),
			(N'RemoveKnowledgeType_PermissionFailed', N'Error'),
			(N'SetKnowledgeTypeEvaluationType', N'Trace'),
			(N'SetKnowledgeTypeEvaluationType_PermissionFailed', N'Error'),
			(N'SetKnowledgeTypeEvaluators', N'Trace'),
			(N'SetKnowledgeTypeEvaluators_PermissionFailed', N'Error'),
			(N'SetKnowledgeTypePreEvaluateByOwner', N'Trace'),
			(N'SetKnowledgeTypePreEvaluateByOwner_PermissionFailed', N'Error'),
			(N'SetKnowledgeTypeForceEvaluatorsDescribe', N'Trace'),
			(N'SetKnowledgeTypeForceEvaluatorsDescribe_PermissionFailed', N'Error'),
			(N'SetKnowledgeTypeNodeSelectType', N'Trace'),
			(N'SetKnowledgeTypeNodeSelectType_PermissionFailed', N'Error'),
			(N'SetKnowledgeTypeSearchabilityType', N'Trace'),
			(N'SetKnowledgeTypeSearchabilityType_PermissionFailed', N'Error'),
			(N'SetKnowledgeTypeScoreScale', N'Trace'),
			(N'SetKnowledgeTypeScoreScale_PermissionFailed', N'Error'),
			(N'SetKnowledgeTypeMinAcceptableScore', N'Trace'),
			(N'SetKnowledgeTypeMinAcceptableScore_PermissionFailed', N'Error'),
			(N'SetKnowledgeTypeConvertEvaluatorsToExperts', N'Trace'),
			(N'SetKnowledgeTypeConvertEvaluatorsToExperts_PermissionFailed', N'Error'),
			(N'SetKnowledgeTypeCandidateRelations', N'Trace'),
			(N'SetKnowledgeTypeCandidateRelations_PermissionFailed', N'Error'),
			(N'AddKnowledgeTypeQuestion', N'Trace'),
			(N'AddKnowledgeTypeQuestion_PermissionFailed', N'Error'),
			(N'ModifyKnowledgeTypeQuestion', N'Trace'),
			(N'ModifyKnowledgeTypeQuestion_PermissionFailed', N'Error'),
			(N'RemoveKnowledgeTypeQuestion', N'Trace'),
			(N'RemoveKnowledgeTypeQuestion_PermissionFailed', N'Error'),
			(N'RemoveKnowledgeTypeRelatedNodeQuestions', N'Trace'),
			(N'RemoveKnowledgeTypeRelatedNodeQuestions_PermissionFailed', N'Error'),
			(N'MoveKnowledgeTypeQuestion', N'Trace'),
			(N'MoveKnowledgeTypeQuestion_PermissionFailed', N'Error'),
			(N'AddKnowledgeTypeAnswerOption', N'Trace'),
			(N'AddKnowledgeTypeAnswerOption_PermissionFailed', N'Error'),
			(N'ModifyKnowledgeTypeAnswerOption', N'Trace'),
			(N'ModifyKnowledgeTypeAnswerOption_PermissionFailed', N'Error'),
			(N'MoveKnowledgeTypeAnswerOption', N'Trace'),
			(N'MoveKnowledgeTypeAnswerOption_PermissionFailed', N'Error'),
			(N'RemoveKnowledgeTypeAnswerOption', N'Trace'),
			(N'RemoveKnowledgeTypeAnswerOption_PermissionFailed', N'Error'),
			(N'SetKnowledgeTypeQuestionWeight', N'Trace'),
			(N'SetKnowledgeTypeQuestionWeight_PermissionFailed', N'Error'),
			(N'AcceptKnowledge', N'Trace'),
			(N'AcceptKnowledge_PermissionFailed', N'Error'),
			(N'RejectKnowledge', N'Trace'),
			(N'RejectKnowledge_PermissionFailed', N'Error'),
			(N'SendKnowledgeToAdmin', N'Trace'),
			(N'SendKnowledgeToAdmin_PermissionFailed', N'Error'),
			(N'SendKnowledgeBackForRevision', N'Trace'),
			(N'SendKnowledgeBackForRevision_PermissionFailed', N'Error'),
			(N'SendKnowledgeToEvaluators', N'Trace'),
			(N'SendKnowledgeToEvaluators_PermissionFailed', N'Error'),
			(N'KnowledgeEvaluation_PermissionFailed', N'Error'),
			(N'RemoveKnowledgeEvaluator', N'Trace'),
			(N'RemoveKnowledgeEvaluator_PermissionFailed', N'Error'),
			(N'RefuseKnowledgeEvaluation_PermissionFailed', N'Error'),
			(N'TerminateKnowledgeEvaluation', N'Trace'),
			(N'TerminateKnowledgeEvaluation_PermissionFailed', N'Error'),
			(N'ActivateKnowledgeNecessaryItem', N'Trace'),
			(N'ActivateKnowledgeNecessaryItem_PermissionFailed', N'Error'),
			(N'DeactiveKnowledgeNecessaryItem', N'Trace'),
			(N'DeactiveKnowledgeNecessaryItem_PermissionFailed', N'Error'),
			(N'SetMessageTemplate', N'Trace'),
			(N'RemoveMessageTemplate', N'Trace'),
			(N'SetDefaultMessageTemplate', N'Trace'),
			(N'SetPrivacyAudience', N'Trace'),
			(N'SetPrivacyAudience_PermissionFailed', N'Error'),
			(N'AddConfidentialityLevel', N'Trace'),
			(N'AddConfidentialityLevel_PermissionFailed', N'Error'),
			(N'ModifyConfidentialityLevel', N'Trace'),
			(N'ModifyConfidentialityLevel_PermissionFailed', N'Error'),
			(N'RemoveConfidentialityLevel', N'Trace'),
			(N'RemoveConfidentialityLevel_PermissionFailed', N'Error'),
			(N'SetConfidentialityLevel', N'Trace'),
			(N'SetConfidentialityLevel_PermissionFailed', N'Error'),
			(N'UnsetConfidentialityLevel', N'Trace'),
			(N'UnsetConfidentialityLevel_PermissionFailed', N'Error'),
			(N'AddQAWorkFlow', N'Trace'),
			(N'AddQAWorkFlow_PermissionFailed', N'Error'),
			(N'RenameQAWorkFlow', N'Trace'),
			(N'RenameQAWorkFlow_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowDescription', N'Trace'),
			(N'SetQAWorkFlowDescription_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowsOrder_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowInitialCheckNeeded', N'Trace'),
			(N'SetQAWorkFlowInitialCheckNeeded_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowFinalConfirmationNeeded', N'Trace'),
			(N'SetQAWorkFlowFinalConfirmationNeeded_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowActionDeadline', N'Trace'),
			(N'SetQAWorkFlowActionDeadline_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowAnswerBy', N'Trace'),
			(N'SetQAWorkFlowAnswerBy_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowPublishAfter', N'Trace'),
			(N'SetQAWorkFlowPublishAfter_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowRemovableAfterConfirmation', N'Trace'),
			(N'SetQAWorkFlowRemovableAfterConfirmation_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowNodeSelectType', N'Trace'),
			(N'SetQAWorkFlowNodeSelectType_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowDisableComments', N'Trace'),
			(N'SetQAWorkFlowDisableComments_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowDisableQuestionLikes', N'Trace'),
			(N'SetQAWorkFlowDisableQuestionLikes_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowDisableAnswerLikes', N'Trace'),
			(N'SetQAWorkFlowDisableAnswerLikes_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowDisableCommentLikes', N'Trace'),
			(N'SetQAWorkFlowDisableCommentLikes_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowDisableBestAnswer', N'Trace'),
			(N'SetQAWorkFlowDisableBestAnswer_PermissionFailed', N'Error'),
			(N'RemoveQAWorkFlow', N'Trace'),
			(N'RemoveQAWorkFlow_PermissionFailed', N'Error'),
			(N'RecycleQAWorkFlow', N'Trace'),
			(N'RecycleQAWorkFlow_PermissionFailed', N'Error'),
			(N'AddQAWorkFlowAdmin', N'Trace'),
			(N'AddQAWorkFlowAdmin_PermissionFailed', N'Error'),
			(N'RemoveQAWorkFlowAdmin', N'Trace'),
			(N'RemoveQAWorkFlowAdmin_PermissionFailed', N'Error'),
			(N'SetQAWorkFlowCandidateRelations', N'Trace'),
			(N'SetQAWorkFlowCandidateRelations_PermissionFailed', N'Error'),
			(N'CreateFAQCategory', N'Trace'),
			(N'CreateFAQCategory_PermissionFailed', N'Error'),
			(N'RenameFAQCategory', N'Trace'),
			(N'RenameFAQCategory_PermissionFailed', N'Error'),
			(N'MoveFAQCategories', N'Trace'),
			(N'MoveFAQCategories_PermissionFailed', N'Error'),
			(N'SetFAQCategoriesOrder_PermissionFailed', N'Error'),
			(N'RemoveFAQCategories', N'Trace'),
			(N'RemoveFAQCategories_PermissionFailed', N'Error'),
			(N'AddFAQItems', N'Trace'),
			(N'AddFAQItems_PermissionFailed', N'Error'),
			(N'AddQuestionToFAQCategories', N'Trace'),
			(N'AddQuestionToFAQCategories_PermissionFailed', N'Error'),
			(N'RemoveFAQItem', N'Trace'),
			(N'RemoveFAQItem_PermissionFailed', N'Error'),
			(N'SetFAQItemsOrder_PermissionFailed', N'Error'),
			(N'SendQuestion', N'Trace'),
			(N'EditQuestionTitle', N'Trace'),
			(N'EditQuestionTitle_PermissionFailed', N'Error'),
			(N'EditQuestionDescription', N'Trace'),
			(N'EditQuestionDescription_PermissionFailed', N'Error'),
			(N'InitialConfirmQuestion_PermissionFailed', N'Error'),
			(N'ConfirmQuestion', N'Trace'),
			(N'ConfirmQuestion_PermissionFailed', N'Error'),
			(N'SetTheBestAnswer', N'Trace'),
			(N'SetTheBestAnswer_PermissionFailed', N'Error'),
			(N'RemoveQuestion', N'Trace'),
			(N'RemoveQuestion_PermissionFailed', N'Error'),
			(N'AddQuestionTag', N'Trace'),
			(N'AddQuestionTag_PermissionFailed', N'Error'),
			(N'SaveQuestionRelatedNodes', N'Trace'),
			(N'SaveQuestionRelatedNodes_PermissionFailed', N'Error'),
			(N'RemoveQuestionRelatedNodes', N'Trace'),
			(N'RemoveQuestionRelatedNodes_PermissionFailed', N'Error'),
			(N'SendAnswer', N'Trace'),
			(N'SendAnswer_PermissionFailed', N'Error'),
			(N'EditAnswer', N'Trace'),
			(N'EditAnswer_PermissionFailed', N'Error'),
			(N'RemoveAnswer', N'Trace'),
			(N'RemoveAnswer_PermissionFailed', N'Error'),
			(N'SendQAComment', N'Trace'),
			(N'EditQAComment', N'Trace'),
			(N'EditQAComment_PermissionFailed', N'Error'),
			(N'RemoveQAComment', N'Trace'),
			(N'RemoveQAComment_PermissionFailed', N'Error'),
			(N'AddQAKnowledgableUser', N'Trace'),
			(N'AddQAKnowledgableUser_PermissionFailed', N'Error'),
			(N'RemoveQAKnowledgableUser', N'Trace'),
			(N'RemoveQAKnowledgableUser_PermissionFailed', N'Error'),
			(N'SendPost', N'Trace'),
			(N'ModifyPost', N'Trace'),
			(N'RemovePost', N'Trace'),
			(N'SendComment', N'Trace'),
			(N'ModifyComment', N'Trace'),
			(N'RemoveComment', N'Trace'),
			(N'LikePost', N'Trace'),
			(N'DislikePost', N'Trace'),
			(N'UnlikePost', N'Trace'),
			(N'LikeComment', N'Trace'),
			(N'DislikeComment', N'Trace'),
			(N'UnlikeComment', N'Trace'),
			(N'AcceptFriendRequest', N'Trace'),
			(N'RejectFriendRequest', N'Trace'),
			(N'CreateUserGroup', N'Trace'),
			(N'ModifyUserGroup', N'Trace'),
			(N'RemoveUserGroup', N'Trace'),
			(N'AddUserGroupMember', N'Trace'),
			(N'RemoveUserGroupMember', N'Trace'),
			(N'SetUserGroupPermission', N'Trace'),
			(N'RemoveUserGroupPermission', N'Trace'),
			(N'SetUserGeneralInfo', N'Trace'),
			(N'Login_Failed', N'Error'),
			(N'SetFirstAndLastName', N'Trace'),
			(N'SetUserName', N'Trace'),
			(N'SetUserIsApproved', N'Trace'),
			(N'SetJobTitle', N'Trace'),
			(N'SetEmploymentType', N'Trace'),
			(N'SetBirthday', N'Trace'),
			(N'SetPhoneNumber', N'Trace'),
			(N'ModifyPhoneNumber', N'Trace'),
			(N'RemovePhoneNumber', N'Trace'),
			(N'SetMainPhoneNumber', N'Trace'),
			(N'SetEmailAddress', N'Trace'),
			(N'ModifyEmailAddress', N'Trace'),
			(N'RemoveEmailAddress', N'Trace'),
			(N'SetMainEmailAddress', N'Trace'),
			(N'Wiki_AccessDenied', N'Error'),
			(N'AddWikiTitle', N'Trace'),
			(N'AddWikiTitle_PermissionFailed', N'Error'),
			(N'ModifyWikiTitle', N'Trace'),
			(N'ModifyWikiTitle_PermissionFailed', N'Error'),
			(N'SetWikiTitlesOrder', N'Trace'),
			(N'SetWikiTitlesOrder_PermissionFailed', N'Error'),
			(N'RemoveWikiTitle', N'Trace'),
			(N'RemoveWikiTitle_PermissionFailed', N'Error'),
			(N'RecycleWikiTitle', N'Trace'),
			(N'RecycleWikiTitle_PermissionFailed', N'Error'),
			(N'AddWikiParagraph', N'Trace'),
			(N'AddWikiParagraph_PermissionFailed', N'Error'),
			(N'ModifyWikiParagraph', N'Trace'),
			(N'ModifyWikiParagraph_PermissionFailed', N'Error'),
			(N'SuggestWikiParagraphChange_PermissionFailed', N'Error'),
			(N'RemoveWikiParagraph', N'Trace'),
			(N'RemoveWikiParagraph_PermissionFailed', N'Error'),
			(N'RecycleWikiParagraph', N'Trace'),
			(N'RecycleWikiParagraph_PermissionFailed', N'Error'),
			(N'SetWikiParagraphsOrder', N'Trace'),
			(N'SetWikiParagraphsOrder_PermissionFailed', N'Error'),
			(N'AcceptWikiParagraphChange', N'Trace'),
			(N'AcceptWikiParagraphChange_PermissionFailed', N'Error'),
			(N'RejectWikiParagraphChange', N'Trace'),
			(N'RejectWikiParagraphChange_PermissionFailed', N'Error'),
			(N'RemoveWikiParagraphChange', N'Trace'),
			(N'RemoveWikiParagraphChange_PermissionFailed', N'Error'),
			(N'CreateState', N'Trace'),
			(N'CreateState_PermissionFailed', N'Error'),
			(N'ModifyState', N'Trace'),
			(N'ModifyState_PermissionFailed', N'Error'),
			(N'RemoveState', N'Trace'),
			(N'RemoveState_PermissionFailed', N'Error'),
			(N'CreateWorkFlow', N'Trace'),
			(N'CreateWorkFlow_PermissionFailed', N'Error'),
			(N'ModifyWorkFlow', N'Trace'),
			(N'ModifyWorkFlow_PermissionFailed', N'Error'),
			(N'RemoveWorkFlow', N'Trace'),
			(N'RemoveWorkFlow_PermissionFailed', N'Error'),
			(N'GetWorkFlow_PermissionFailed', N'Error'),
			(N'AddWorkFlowState', N'Trace'),
			(N'AddWorkFlowState_PermissionFailed', N'Error'),
			(N'RemoveWorkFlowState', N'Trace'),
			(N'RemoveWorkFlowState_PermissionFailed', N'Error'),
			(N'ModifyWorkFlowStateDescription', N'Trace'),
			(N'ModifyWorkFlowStateDescription_PermissionFailed', N'Error'),
			(N'SetWorkFlowStateTag', N'Trace'),
			(N'SetWorkFlowStateTag_PermissionFailed', N'Error'),
			(N'RemoveWorkFlowStateTag', N'Trace'),
			(N'RemoveWorkFlowStateTag_PermissionFailed', N'Error'),
			(N'SetWorkFlowStateDirector', N'Trace'),
			(N'SetWorkFlowStateDirector_PermissionFailed', N'Error'),
			(N'SetWorkFlowStatePoll', N'Trace'),
			(N'SetWorkFlowStatePoll_PermissionFailed', N'Error'),
			(N'SetWorkFlowStateDataNeedsType', N'Trace'),
			(N'SetWorkFlowStateDataNeedsType_PermissionFailed', N'Error'),
			(N'SetWorkFlowStateDataNeedsDescription', N'Trace'),
			(N'SetWorkFlowStateDataNeedsDescription_PermissionFailed', N'Error'),
			(N'SetWorkFlowStateDescriptionAsNeeded', N'Trace'),
			(N'SetWorkFlowStateDescriptionAsNeeded_PermissionFailed', N'Error'),
			(N'SetWorkFlowStateDescriptionAsNotNeeded', N'Trace'),
			(N'SetWorkFlowStateDescriptionAsNotNeeded_PermissionFailed', N'Error'),
			(N'SetWorkFlowStateHideOwnerNameAsNeeded', N'Trace'),
			(N'SetWorkFlowStateHideOwnerNameAsNeeded_PermissionFailed', N'Error'),
			(N'SetWorkFlowStateHideOwnerNameAsNotNeeded', N'Trace'),
			(N'SetWorkFlowStateHideOwnerNameAsNotNeeded_PermissionFailed', N'Error'),
			(N'SetWorkFlowStateEditPermission', N'Trace'),
			(N'SetWorkFlowStateEditPermission_PermissionFailed', N'Error'),
			(N'SetDataNeedRequestsAsFree', N'Trace'),
			(N'SetDataNeedRequestsAsFree_PermissionFailed', N'Error'),
			(N'SetDataNeedRequestsAsNotFree', N'Trace'),
			(N'SetDataNeedRequestsAsNotFree_PermissionFailed', N'Error'),
			(N'SetStateDataNeed', N'Trace'),
			(N'SetStateDataNeed_PermissionFailed', N'Error'),
			(N'RemoveStateDataNeed', N'Trace'),
			(N'RemoveStateDataNeed_PermissionFailed', N'Error'),
			(N'SetRejectionSettings', N'Trace'),
			(N'SetRejectionSettings_PermissionFailed', N'Error'),
			(N'SetMaxAllowedRejections', N'Trace'),
			(N'SetMaxAllowedRejections_PermissionFailed', N'Error'),
			(N'SetStateDataNeedInstanceAsFilled', N'Trace'),
			(N'SetStateDataNeedInstanceAsFilled_PermissionFailed', N'Error'),
			(N'SetStateDataNeedInstanceAsNotFilled', N'Trace'),
			(N'SetStateDataNeedInstanceAsNotFilled_PermissionFailed', N'Error'),
			(N'RemoveStateDataNeedInstance', N'Trace'),
			(N'RemoveStateDataNeedInstance_PermissionFailed', N'Error'),
			(N'AddStateConnection', N'Trace'),
			(N'AddStateConnection_PermissionFailed', N'Error'),
			(N'MoveStateConnectionUp', N'Trace'),
			(N'MoveStateConnectionUp_PermissionFailed', N'Error'),
			(N'MoveStateConnectionDown', N'Trace'),
			(N'MoveStateConnectionDown_PermissionFailed', N'Error'),
			(N'RemoveStateConnection', N'Trace'),
			(N'RemoveStateConnection_PermissionFailed', N'Error'),
			(N'SetStateConnectionLabel', N'Trace'),
			(N'SetStateConnectionLabel_PermissionFailed', N'Error'),
			(N'SetStateConnectionAttachmentStatus', N'Trace'),
			(N'SetStateConnectionAttachmentStatus_PermissionFailed', N'Error'),
			(N'SetStateConnectionDirector', N'Trace'),
			(N'SetStateConnectionDirector_PermissionFailed', N'Error'),
			(N'SetStateConnectionForm', N'Trace'),
			(N'SetStateConnectionForm_PermissionFailed', N'Error'),
			(N'RemoveStateConnectionForm', N'Trace'),
			(N'RemoveStateConnectionForm_PermissionFailed', N'Error'),
			(N'AddAutoMessage', N'Trace'),
			(N'AddAutoMessage_PermissionFailed', N'Error'),
			(N'ModifyAutoMessage', N'Trace'),
			(N'ModifyAutoMessage_PermissionFailed', N'Error'),
			(N'RemoveAutoMessage', N'Trace'),
			(N'RemoveAutoMessage_PermissionFailed', N'Error'),
			(N'TerminateWorkFlow', N'Trace'),
			(N'TerminateWorkFlow_PermissionFailed', N'Error'),
			(N'RestartWorkFlow_PermissionFailed', N'Error'),
			(N'AddOwnerWorkFlow', N'Trace'),
			(N'AddOwnerWorkFlow_PermissionFailed', N'Error'),
			(N'RemoveOwnerWorkFlow', N'Trace'),
			(N'RemoveOwnerWorkFlow_PermissionFailed', N'Error'),
			(N'NotAuthorizedAnonymousRequest', N'Warn'),
			(N'PotentialCSRFAttack', N'Warn'),
			(N'PotentialReplayAttack', N'Warn'),
			(N'JobStarted', N'Info'),
			(N'UserLockedOut', N'Info'),
			(N'Download', N'Trace'),
			(N'KnowledgeEvaluation', N'Trace'),
			(N'RefuseKnowledgeEvaluation', N'Trace'),
			(N'InitialConfirmQuestion', N'Trace'),
			(N'SharePost', N'Trace'),
			(N'Search', N'Trace'),
			(N'Login', N'Trace'),
			(N'Logout', N'Trace'),
			(N'SuggestWikiParagraphChange', N'Trace'),
			(N'RestartWorkFlow', N'Trace')

	UPDATE L
		SET [Level] = I.[Level]
	FROM [dbo].[LG_Logs] AS L
		INNER JOIN @Items AS I
		ON I.[Action] = L.[Action]
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	UPDATE L
		SET [Level] = N'Trace'
	FROM [dbo].[LG_Logs] AS L
	WHERE L.[Level] IS NULL
END
GO


IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	DECLARE @Items TABLE ([Action] varchar(100), [Level] varchar(20))

	INSERT INTO @Items ([Action], [Level])
	VALUES	(N'ExportReportToExcel', N'Fatal'),
			(N'JobFailed', N'Fatal'),
			(N'ExtractFormsFromXML', N'Fatal'),
			(N'InitSearchIndexDocuments', N'Fatal'),
			(N'IndexUpdateJob', N'Fatal')

	UPDATE L
		SET [Level] = I.[Level]
	FROM [dbo].[LG_ErrorLogs] AS L
		INNER JOIN @Items AS I
		ON I.[Action] = L.[Subject]
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	UPDATE L
		SET [Level] = N'Debug'
	FROM [dbo].[LG_ErrorLogs] AS L
	WHERE L.[Level] IS NULL
END
GO


IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.25.2.0' BEGIN
	UPDATE [dbo].[AppSetting]
		SET [Version] = 'v28.28.8.1' -- 13971112
END
GO


