USE [EKM_App]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	SET ANSI_PADDING ON
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	ALTER TABLE [dbo].[USR_PasswordsHistory]
	ADD [AutoGenerated] bit NULL
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	SET ANSI_PADDING OFF
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	ALTER TABLE [dbo].[PRVC_Audience]
	DROP COLUMN [ModificationRight]
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	SET ANSI_PADDING ON
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	ALTER TABLE [dbo].[PRVC_PrivacyType]
	ADD [ConfidentialityID] [uniqueidentifier] NULL
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	ALTER TABLE [dbo].[PRVC_PrivacyType]
	ADD [CalculateHierarchy] [bit] NULL
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN	
	SET ANSI_PADDING OFF
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	EXEC ('DELETE [dbo].[PRVC_PrivacyType] WHERE Deleted = 1')
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	ALTER TABLE [dbo].[PRVC_PrivacyType]
	DROP COLUMN [Deleted]
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	ALTER TABLE [dbo].[PRVC_PrivacyType]  WITH CHECK ADD  CONSTRAINT [FK_PRVC_PrivacyType_PRVC_ConfidentialityLevels] FOREIGN KEY([ConfidentialityID])
	REFERENCES [dbo].[PRVC_ConfidentialityLevels] ([ID])
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	ALTER TABLE [dbo].[PRVC_PrivacyType] CHECK CONSTRAINT [FK_PRVC_PrivacyType_PRVC_ConfidentialityLevels]
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	UPDATE T
		SET ConfidentialityID = C.LevelID
	FROM [dbo].[PRVC_PrivacyType] AS T
		INNER JOIN [dbo].[PRVC_Confidentialities] AS C
		ON C.ApplicationID = T.ApplicationID AND C.ItemID = T.ObjectID
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	INSERT INTO [dbo].[PRVC_PrivacyType] (ApplicationID, ObjectID, ConfidentialityID, PrivacyType, 
		CreatorUserID, CreationDate, LastModifierUserID, LastModificationDate)
	SELECT C.ApplicationID, C.ItemID, C.LevelID, N'', C.CreatorUserID, C.CreationDate,
		C.LastModifierUserID, C.LastModificationDate
	FROM [dbo].[PRVC_PrivacyType] AS P
		RIGHT JOIN (
			SELECT	X.ApplicationID, 
					X.ItemID,
					CAST(MAX(CAST(X.LevelID AS varchar(50))) AS uniqueidentifier) AS LevelID,
					CAST(MAX(CAST(X.CreatorUserID AS varchar(50))) AS uniqueidentifier) AS CreatorUserID,
					MAX(X.CreationDate) AS CreationDate,
					CAST(MAX(CAST(X.LastModifierUserID AS varchar(50))) AS uniqueidentifier) AS LastModifierUserID,
					MAX(X.LastModificationDate) AS LastModificationDate
			FROM [dbo].[PRVC_Confidentialities] AS X
			GROUP BY X.ApplicationID, X.ItemID
		) AS C
		ON C.ApplicationID = P.ApplicationID AND C.ItemID = P.ObjectID
	WHERE P.ObjectID IS NULL
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	IF EXISTS(select * FROM sys.views where name = 'PRVC_View_Confidentialities')
	DROP VIEW [dbo].[PRVC_View_Confidentialities]
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	DROP TABLE [dbo].[PRVC_Confidentialities]
END
GO

IF (SELECT TOP(1) X.[Version] FROM [dbo].[AppSetting] AS X) = N'v28.24.21.2' BEGIN
	UPDATE [dbo].[AppSetting]
		SET [Version] = 'v28.24.24.0' -- 13970801
END
GO