USE master
GO

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'hrdovjshjpvjo'

CREATE CERTIFICATE tdeCert WITH SUBJECT = 'TDE Certificate'

BACKUP CERTIFICATE tdeCert TO FILE = 'G:\rv_cert'
WITH PRIVATE KEY(
	FILE = 'G:\rv_prvt_cert',
	ENCRYPTION BY PASSWORD = 'raminyavari'
)

USE EKM_App
GO

-- Database Encryption
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE tdeCert

ALTER DATABASE [EKM_App] SET ENCRYPTION ON
GO

ALTER DATABASE [EKM_App] SET ENCRYPTION OFF
GO
-- end of Database Encryption


-- Column Encryption
CREATE SYMMETRIC KEY CNNameKey
WITH ALGORITHM = AES_256
ENCRYPTION BY CERTIFICATE tdeCert
GO

ALTER TABLE [dbo].[CN_Nodes]
ADD [EncryptName] [varbinary](1000)
GO

OPEN SYMMETRIC KEY CNNameKey
DECRYPTION BY CERTIFICATE tdeCert
GO

UPDATE CN_Nodes
	SET EncryptName = ENCRYPTBYKEY(KEY_GUID('CNNameKey'), Name)
GO

SELECT CONVERT(nvarchar(255), DECRYPTBYKEY(EncryptName)) AS Name
FROM [dbo].[CN_Nodes]
GO

CLOSE SYMMETRIC KEY CNNameKey
GO
-- end of Column Encryption


/* -- Drop Syntax
DROP SYMMETRIC KEY CNNameKey
GO
DROP CERTIFICATE tdeCert
GO
DROP MASTER KEY
GO
*/