//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaaiVanIntermediate.RaaiVanKnowledge {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RaaiVanKnowledge.KnowledgeSoap")]
    public interface KnowledgeSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRelatedKnowledges", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRelatedKnowledges(string nodeId, string nodeTypeId);
        
        // CODEGEN: Parameter 'lowerCreationDateLimit' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchKnowledges", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RaaiVanIntermediate.RaaiVanKnowledge.SearchKnowledgesResponse SearchKnowledges(RaaiVanIntermediate.RaaiVanKnowledge.SearchKnowledgesRequest request);
        
        // CODEGEN: Parameter 'lowerCreationDateLimit' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKnowledgesCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RaaiVanIntermediate.RaaiVanKnowledge.GetKnowledgesCountResponse GetKnowledgesCount(RaaiVanIntermediate.RaaiVanKnowledge.GetKnowledgesCountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchKnowledges", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchKnowledgesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string viewerusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string creatorusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string searchText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Data.DataTable relatedNodes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> lowerCreationDateLimit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> upperCreationDateLimit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> lowerPublicationDateLimit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> upperPublicationDateLimit;
        
        public SearchKnowledgesRequest() {
        }
        
        public SearchKnowledgesRequest(string viewerusername, string creatorusername, string searchText, System.Data.DataTable relatedNodes, System.Nullable<System.DateTime> lowerCreationDateLimit, System.Nullable<System.DateTime> upperCreationDateLimit, System.Nullable<System.DateTime> lowerPublicationDateLimit, System.Nullable<System.DateTime> upperPublicationDateLimit) {
            this.viewerusername = viewerusername;
            this.creatorusername = creatorusername;
            this.searchText = searchText;
            this.relatedNodes = relatedNodes;
            this.lowerCreationDateLimit = lowerCreationDateLimit;
            this.upperCreationDateLimit = upperCreationDateLimit;
            this.lowerPublicationDateLimit = lowerPublicationDateLimit;
            this.upperPublicationDateLimit = upperPublicationDateLimit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchKnowledgesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchKnowledgesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable SearchKnowledgesResult;
        
        public SearchKnowledgesResponse() {
        }
        
        public SearchKnowledgesResponse(System.Data.DataTable SearchKnowledgesResult) {
            this.SearchKnowledgesResult = SearchKnowledgesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKnowledgesCount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKnowledgesCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string viewerusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string creatorusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string searchText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Data.DataTable relatedNodes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> lowerCreationDateLimit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> upperCreationDateLimit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> lowerPublicationDateLimit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> upperPublicationDateLimit;
        
        public GetKnowledgesCountRequest() {
        }
        
        public GetKnowledgesCountRequest(string viewerusername, string creatorusername, string searchText, System.Data.DataTable relatedNodes, System.Nullable<System.DateTime> lowerCreationDateLimit, System.Nullable<System.DateTime> upperCreationDateLimit, System.Nullable<System.DateTime> lowerPublicationDateLimit, System.Nullable<System.DateTime> upperPublicationDateLimit) {
            this.viewerusername = viewerusername;
            this.creatorusername = creatorusername;
            this.searchText = searchText;
            this.relatedNodes = relatedNodes;
            this.lowerCreationDateLimit = lowerCreationDateLimit;
            this.upperCreationDateLimit = upperCreationDateLimit;
            this.lowerPublicationDateLimit = lowerPublicationDateLimit;
            this.upperPublicationDateLimit = upperPublicationDateLimit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKnowledgesCountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKnowledgesCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetKnowledgesCountResult;
        
        public GetKnowledgesCountResponse() {
        }
        
        public GetKnowledgesCountResponse(int GetKnowledgesCountResult) {
            this.GetKnowledgesCountResult = GetKnowledgesCountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KnowledgeSoapChannel : RaaiVanIntermediate.RaaiVanKnowledge.KnowledgeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KnowledgeSoapClient : System.ServiceModel.ClientBase<RaaiVanIntermediate.RaaiVanKnowledge.KnowledgeSoap>, RaaiVanIntermediate.RaaiVanKnowledge.KnowledgeSoap {
        
        public KnowledgeSoapClient() {
        }
        
        public KnowledgeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KnowledgeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KnowledgeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KnowledgeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetRelatedKnowledges(string nodeId, string nodeTypeId) {
            return base.Channel.GetRelatedKnowledges(nodeId, nodeTypeId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RaaiVanIntermediate.RaaiVanKnowledge.SearchKnowledgesResponse RaaiVanIntermediate.RaaiVanKnowledge.KnowledgeSoap.SearchKnowledges(RaaiVanIntermediate.RaaiVanKnowledge.SearchKnowledgesRequest request) {
            return base.Channel.SearchKnowledges(request);
        }
        
        public System.Data.DataTable SearchKnowledges(string viewerusername, string creatorusername, string searchText, System.Data.DataTable relatedNodes, System.Nullable<System.DateTime> lowerCreationDateLimit, System.Nullable<System.DateTime> upperCreationDateLimit, System.Nullable<System.DateTime> lowerPublicationDateLimit, System.Nullable<System.DateTime> upperPublicationDateLimit) {
            RaaiVanIntermediate.RaaiVanKnowledge.SearchKnowledgesRequest inValue = new RaaiVanIntermediate.RaaiVanKnowledge.SearchKnowledgesRequest();
            inValue.viewerusername = viewerusername;
            inValue.creatorusername = creatorusername;
            inValue.searchText = searchText;
            inValue.relatedNodes = relatedNodes;
            inValue.lowerCreationDateLimit = lowerCreationDateLimit;
            inValue.upperCreationDateLimit = upperCreationDateLimit;
            inValue.lowerPublicationDateLimit = lowerPublicationDateLimit;
            inValue.upperPublicationDateLimit = upperPublicationDateLimit;
            RaaiVanIntermediate.RaaiVanKnowledge.SearchKnowledgesResponse retVal = ((RaaiVanIntermediate.RaaiVanKnowledge.KnowledgeSoap)(this)).SearchKnowledges(inValue);
            return retVal.SearchKnowledgesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RaaiVanIntermediate.RaaiVanKnowledge.GetKnowledgesCountResponse RaaiVanIntermediate.RaaiVanKnowledge.KnowledgeSoap.GetKnowledgesCount(RaaiVanIntermediate.RaaiVanKnowledge.GetKnowledgesCountRequest request) {
            return base.Channel.GetKnowledgesCount(request);
        }
        
        public int GetKnowledgesCount(string viewerusername, string creatorusername, string searchText, System.Data.DataTable relatedNodes, System.Nullable<System.DateTime> lowerCreationDateLimit, System.Nullable<System.DateTime> upperCreationDateLimit, System.Nullable<System.DateTime> lowerPublicationDateLimit, System.Nullable<System.DateTime> upperPublicationDateLimit) {
            RaaiVanIntermediate.RaaiVanKnowledge.GetKnowledgesCountRequest inValue = new RaaiVanIntermediate.RaaiVanKnowledge.GetKnowledgesCountRequest();
            inValue.viewerusername = viewerusername;
            inValue.creatorusername = creatorusername;
            inValue.searchText = searchText;
            inValue.relatedNodes = relatedNodes;
            inValue.lowerCreationDateLimit = lowerCreationDateLimit;
            inValue.upperCreationDateLimit = upperCreationDateLimit;
            inValue.lowerPublicationDateLimit = lowerPublicationDateLimit;
            inValue.upperPublicationDateLimit = upperPublicationDateLimit;
            RaaiVanIntermediate.RaaiVanKnowledge.GetKnowledgesCountResponse retVal = ((RaaiVanIntermediate.RaaiVanKnowledge.KnowledgeSoap)(this)).GetKnowledgesCount(inValue);
            return retVal.GetKnowledgesCountResult;
        }
    }
}
