USE [EKM_App]
GO


CREATE TABLE [dbo].[USR_PassResetTickets](
	[UserID]		UNIQUEIDENTIFIER NOT NULL,
	[Ticket]		UNIQUEIDENTIFIER NOT NULL
 CONSTRAINT [PK_USR_PassResetTickets] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[USR_PassResetTickets]  WITH CHECK ADD  CONSTRAINT [FK_USR_PassResetTickets_aspnet_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[aspnet_Users] ([UserId])
GO

ALTER TABLE [dbo].[USR_PassResetTickets] CHECK CONSTRAINT [FK_USR_PassResetTickets_aspnet_Users]
GO
