USE [EKM_App]
GO


CREATE TABLE [dbo].[USR_PasswordsHistory](
	[ID]		[bigint] NOT NULL IDENTITY(1, 1),
	[UserID]	[uniqueidentifier] NOT NULL,
	[Password]	[nvarchar] (256) NOT NULL,
	[SetDate]	[datetime] NOT NULL
CONSTRAINT [PK_USR_PasswordsHistory] PRIMARY KEY CLUSTERED
(
	[ID] ASC 
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USR_PasswordsHistory] ADD  CONSTRAINT [UK_USR_PasswordsHistory] UNIQUE NONCLUSTERED 
(
	[UserID]	ASC,
	[ID]		ASC,
	[Password]	ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


