USE [EKM_App]
GO


CREATE TABLE [dbo].[USR_TemporaryUsers](
	[UserID]			UNIQUEIDENTIFIER NOT NULL,
	[UserName]			NVARCHAR (255) NOT NULL,
	[FirstName]			NVARCHAR (255) NULL,
	[LastName]			NVARCHAR (255) NULL,
	[Password]			NVARCHAR (255) NULL,
	[PasswordSalt]		NVARCHAR (255) NULL,
	[EMail]				NVARCHAR (255) NULL,
	[CreationDate]		DATETIME NOT NULL,
	[ExpirationDate]	DATETIME NULL,
	[ActivationCode]	VARCHAR (255) NULL
 CONSTRAINT [PK_USR_TemporaryUsers] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
