USE [EKM_App]
GO


IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[DCT_Files]') AND name = N'IX_DCT_Files_OwnerID')
DROP INDEX [IX_DCT_Files_OwnerID] ON [dbo].[DCT_Files] WITH ( ONLINE = OFF )
GO

CREATE NONCLUSTERED INDEX [IX_DCT_Files_OwnerID] ON [dbo].[DCT_Files] 
(
	[OwnerID] ASC,
	[ApplicationID] ASC,
	[OwnerType] ASC,
	[FileNameGuiD] ASC,
	[Deleted] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO